"""
拼写检查和语法检测工具
类似于 Word 的拼写/语法校对功能
"""
import re
from pathlib import Path
from spellchecker import SpellChecker

# 初始化英文拼写检查器
spell = SpellChecker(language='en')

_JOINER_SMALL_WORDS = {
    'a', 'an', 'and', 'as', 'at', 'be', 'by', 'for', 'from', 'if', 'in', 'into',
    'is', 'it', 'of', 'on', 'or', 'out', 'than', 'that', 'the', 'to', 'up', 'with',
}

_PDF_TECH_FRAGMENTS = {
    'dnb', 'dna', 'rna', 'coli', 'well', 'plate', 'buffer', 'library', 'sample',
    'reagent', 'kit', 'seq', 'mgi', 'sscir', 'dsdna', 'oligreen', 'qubit', 'contents',
}

_PDF_SPELL_SKIP_WORDS = {
    'transcranial', 'anonymization', 'jpg', 'fps', 'snr', 'tib', 'vrms', 'ghz', 'tis', 'pag', 'mproper',
}

DOMAIN_ABBREVIATIONS = {
    'audt', 'auth', 'alof', 'dtbk', 'emrg', 'didt', 'paut', 'plok', 'sgud', 'rdmp',
    'imt', 'mi', 'ti', 'prf', 'ri', 'pi', 'sd', 'roi', 'fov', 'tgc',
    'ac', 'fl', 'hc', 'bpd', 'thd', 'apad', 'aptd', 'ttd', 'fta',
    'lvids', 'lvid', 'ef', 'clv', 'cle', 'clt', 'ef6', 'ef6-clv', 'ef6-cle', 'ef6-clt',
    'mah', 'mwh', 'vdc', 'vac', 'https', 'http', 'tcp', 'kcp', 'bmu', 'fda', 'iec', 'emc', 'rf', 'alara',
    'jpg', 'fps', 'snr', 'tib', 'vrms', 'ghz', 'tis', 'pag',
}

# 技术文档常用术语白名单
TECH_TERMS_WHITELIST = {
    'DNA', 'RNA', 'PCR', 'ELISA', 'IVD', 'FDA', 'CE', 'ISO', 'IEC',
    'QC', 'QA', 'R&D', 'PDF', 'HTML', 'XML', 'API', 'GUI', 'CLI',
    'USB', 'HDMI', 'LED', 'LCD', 'OLED', 'UV', 'IR', 'RF', 'EM',
    'ATP', 'CT', 'MRI', 'PET', 'ICU', 'ED', 'Rx', 'OTC',
    'MGI', 'BGISEQ', 'DNBSEQ', 'DNB', 'cPAS', 'CoolMPS',
    'Ltd', 'Inc', 'Corp', 'Co', 'Mr', 'Mrs', 'Ms', 'Dr', 'Prof',
    'eg', 'ie', 'etc', 'et al', 'vs', 'approx',
    'figs', 'fig', 'no', 'Nos',
    'Wuhan', 'Beijing', 'Shanghai', 'Shenzhen', 'China',
    'min', 'hr', 'sec', 'hrs', 'mins', 'secs',
    'ml', 'ul', 'l', 'dl', 'mg', 'ug', 'kg', 'g',
    'mm', 'cm', 'nm', 'um', 'pm', 'km',
    'rpm', 'pH',
    'A', 'mA', 'uA', 'V', 'mV', 'W', 'mW', 'kW',
    'nt', 'bp', 'kb', 'Mb', 'Gb',
    'ID', 'IV', 'IM', 'IP', 'SC', 'PO', 'PRN', 'QD', 'BID', 'TID', 'QID',
    'IgG', 'IgM', 'IgA', 'IgE', 'IgD', 'IgY',
    'Ab', 'Abs', 'Ag', 'Ags', 'mAb', 'mAbs',
    'HPLC', 'GC', 'MS', 'LC-MS', 'GC-MS', 'NMR', 'UV-Vis',
    'EDTA', 'PBS', 'TBS', 'PBST', 'TBST', 'SSC', 'SSPE',
    'BSA', 'DMSO', 'DMF', 'THF', 'MeOH', 'EtOH', 'IPA',
    'SDS', 'PAGE', 'Western',
    'IHC', 'ICC', 'IF', 'FISH', 'ISH', 'ELISPOT',
    'FACS', 'FCM',
    'app', 'apps', 'etc',
    'barcode', 'thermo', 'onestep', 'dsdna', 'invitrogen', 'axygen', 'wfex',
    'MGISP', 'MGISP-960', 'MGISP-100', 'MGISP-Smart', 'MGICLab', 'MGICLab-FZ90', 'MGICLab-FZ150K',
    'MGISEQ', 'DNBelab', 'DNBelab-D4RS', 'DIPSEQ', 'StereOmics', 'GenSIRO', 'DNBs', 'ssCir',
    'cDNA', 'gDNA', 'cfDNA', 'ctDNA', 'FFPE', 'WGS', 'WES', 'RNA-seq', 'ChIP-seq', 'ATAC-seq',
    'qPCR', 'dPCR', 'NGS', 'SBS', 'OliGreen', 'Quant-iT', 'RiboGreen', 'PicoGreen', 'Qubit',
    'App-D', 'OS-SB', 'OS-DB', 'OS-App', 'aliquoting', 'quantitation', 'quantification',
    'oligonucleotide', 'uncyclized', 'microplates', 'vortexing', 'pipetting', 'centrifuging',
    'hybridization', 'denaturation', 'annealing', 'elongation', 'amplicon', 'multiplexing',
    'barcoding', 'pooling', 'normalization', 'titration', 'supernatant', 'precipitate', 'elution',
    'lysis', 'aliquots', 'WDesigner', 'Consumables.sp960', 'sp960', 'BWA', 'GATK', 'SAMtools',
    'BLAST', 'Bowtie', 'STAR', 'HISAT2', 'SPAdes', 'SOAPdenovo', 'FastQC', 'MultiQC', 'Trimmomatic',
    'Cutadapt', 'Seurat', 'Scanpy', 'NCBI', 'EMBL', 'DDBJ', 'Ensembl', 'UCSC', 'RefSeq', 'dbSNP',
    'dbGaP', 'GEO', 'SRA', 'COSMIC', 'ClinVar', 'OMIM', 'UniProt', 'PDB', 'nM', 'μM', 'mM',
    'RUO', 'IVDR', 'RoHS', 'WEEE', 'FCL', 'workflow', 'desktop', 'login', 'logout', 'Hamilton',
    'HamiLton', 'Eppendorf', 'Fisher', 'LABTECH', 'Fluostar', 'Omega', 'BL21', 'DH5α', 'Greiner',
    'Bio-One', 'ssDNA', 'Oligreen', 'g-force', 'in vitro', 'in vivo', 'in situ', 'ex vivo', 'de novo',
    'e.g', 'i.e', 'P.R', 'R.P', 'U.S.A', 'U.S', 'U.K',
    'Ltd.', 'Co.', 'Inc.', 'LLC.', 'LLP.', 'Corp.',
    'Mr.', 'Mrs.', 'Ms.', 'Dr.', 'Prof.',
    'DNBSEQ-T20×2RS', 'DNBSEQ-T7', 'DNBSEQ-G400', 'MGISP-Smart 8', 'RCR', 'OneStep', 'High-throughput',
    'Run Wizard', 'Cell Ranger', 'fluorometer', 'luminescence', 'chemiluminescence', 'nucleotide',
    'nuclease', 'polymerase', 'ligase', 'vector', 'plasmid', 'genome', 'transcriptome', 'proteome',
    'metabolome', 'diploid', 'haploid', 'polyploid', 'transformation', 'transfection', 'transduction',
    'cloning', 'fluorescence', 'purification', 'centrifugation', 'electrophoresis', 'chromatography',
    'spectrophotometer', 'restriction', 'fragmentation', 'mutation', 'allele', 'genotype', 'phenotype',
    'haplotype', 'phylogenetic', 'homologous', 'orthologous', 'paralogous', 'heterologous', 'polymorphism',
    'BMG', 'coli', 'pre', 'tech', 'AXYGEN', 'Thermo Fisher Scientific',
    'metagenomics', 'thermocycler', 'thermocyclers', 'multiplexing',
    'circularization', 'adapter', 'ligation', 'elute', 'enhancer', 'vortexer',
    'vortex', 'vortexes', 'Agilent', 'ALPAQUA', 'Ambion', 'Axygen', 'Covaris',
    'DynaMag', 'PerkinElmer', 'Invitrogen', 'ThermoFisher', 'CompleteGenomics',
    'Illumina', 'NEB', 'Takara', 'Qiagen', 'thaliana', 'saliva', 'ssDNA',
    'TE Buffer', 'En-TE', 'En-Beads', 'Bioanalyzer', 'Quant-iT',
    'Tris', 'CSS', 'UDB', 'fmol', 'fragmentase', 'repurification',
    'demultiplexing', 'techsupport', 'sativa', 'barcodes', 'RXN', 'PF',
}

SPELLCHECK_WHITELIST = {
    'exact': {
        'hengyunshan', 'guanggu', 'qingdao', 'shandong',
        'hamilton', 'eppendorf', 'axygen', 'greiner',
        'dnbseq', 'mgisp', 'dnv', 'app-d', 'stereomics', 'dipseq',
        'dnase', 'rnase', 'oligodt', 'qubit', 'pcr',
        'dhs', 'bio', 'one', 'mgi', 'sto', 'sscir', 'dsdna',
        'buffer', 'greiner', 'hamilton', 'mgitech', 'life', 'science',
        'te',
    },
    'prefix': {'os-', 'app-', 't20-', 'mgisp-', 'dnbseq-'},
    'pattern': [
        (r'^[A-Z]{1,3}-\d{3}-\d{6}-\d{2}$', '产品编号'),
        (r'^\d+\.\d+$', '版本号'),
        (r'^[A-Za-z]+-[A-Za-z]+-V\d+(?:\.\d+)*$', '软件版本型号'),
        (r'^[A-Z]{2,}\d*(?:-[A-Za-z0-9]+)+$', '产品型号'),
    ],
}

_DICTIONARY_DIR = Path(__file__).resolve().parents[1] / 'dictionary'


def _load_dictionary_file(name):
    path = _DICTIONARY_DIR / name
    if not path.exists():
        return set()
    terms = set()
    for line in path.read_text(encoding='utf-8').splitlines():
        term = line.strip()
        if term and not term.startswith('#'):
            terms.add(term)
    return terms


EXTERNAL_TECH_TERMS = _load_dictionary_file('technical_terms.txt')
EXTERNAL_TRADEMARKS = _load_dictionary_file('trademarks.txt')
_TECH_TERMS_NORMALIZED = {str(term).lower() for term in TECH_TERMS_WHITELIST | EXTERNAL_TECH_TERMS | EXTERNAL_TRADEMARKS}


def _load_whitelist_into_dictionary():
    words = set()
    for term in TECH_TERMS_WHITELIST | EXTERNAL_TECH_TERMS | EXTERNAL_TRADEMARKS:
        for piece in re.findall(r"[A-Za-z]+", str(term)):
            if len(piece) >= 2:
                words.add(piece.lower())
    spell.word_frequency.load_words(sorted(words))


_load_whitelist_into_dictionary()


def is_whitelisted(word: str) -> bool:
    candidate = str(word or '').strip()
    lowered = candidate.lower()
    if _is_protected_technical_token(candidate):
        return True
    if lowered in SPELLCHECK_WHITELIST['exact']:
        return True
    for prefix in SPELLCHECK_WHITELIST['prefix']:
        if lowered.startswith(prefix):
            return True
    for pattern, _ in SPELLCHECK_WHITELIST['pattern']:
        if re.match(pattern, candidate):
            return True
    return False


def _is_protected_technical_token(word: str) -> bool:
    token = str(word or '').strip().strip('.,;:()[]{}"\'®™©')
    lowered = token.lower()
    if not lowered:
        return False
    if lowered in _TECH_TERMS_NORMALIZED:
        return True
    if re.fullmatch(r'\d+(?:\.\d+)?[xX]', token):
        return True
    if re.fullmatch(r'(?:step|table|figure)\s*\d+', token, re.IGNORECASE):
        return True
    if re.fullmatch(r'[A-Za-z]+(?:-[A-Za-z0-9]+)+', token):
        return True
    return False

# 常见拼写错误映射表
COMMON_MISSPELLINGS = {
    'accomodate': 'accommodate',
    'acheive': 'achieve',
    'acheived': 'achieved',
    'acheiving': 'achieving',
    'acquiantance': 'acquaintance',
    'advertisment': 'advertisement',
    'agressive': 'aggressive',
    'allready': 'already',
    'alot': 'a lot',
    'amature': 'amateur',
    'annonymous': 'anonymous',
    'apparant': 'apparent',
    'appearence': 'appearance',
    'articel': 'article',
    'begining': 'beginning',
    'beleive': 'believe',
    'beleived': 'believed',
    'beleiving': 'believing',
    'beter': 'better',
    'betwen': 'between',
    'bindind': 'binding',
    'buisness': 'business',
    'calender': 'calendar',
    'carefull': 'careful',
    'carreer': 'career',
    'calibratation': 'calibration',
    'certifice': 'certified',
    'charater': 'character',
    'charaters': 'characters',
    'challange': 'challenge',
    'changable': 'changeable',
    'charecter': 'character',
    'cheif': 'chief',
    'collegue': 'colleague',
    'collegues': 'colleagues',
    'comming': 'coming',
    'commitee': 'committee',
    'comparsion': 'comparison',
    'compatable': 'compatible',
    'competance': 'competence',
    'competant': 'competent',
    'complet': 'complete',
    'completly': 'completely',
    'comprable': 'comparable',
    'conceed': 'concede',
    'concious': 'conscious',
    'condamned': 'condemned',
    'confortable': 'comfortable',
    'congradulate': 'congratulate',
    'congradulations': 'congratulations',
    'conscent': 'consent',
    'consious': 'conscious',
    'consistant': 'consistent',
    'constistant': 'consistent',
    'contempory': 'contemporary',
    'convinience': 'convenience',
    'corrct': 'correct',
    'corrrect': 'correct',
    'curiousity': 'curiosity',
    'decribe': 'describe',
    'decribed': 'described',
    'deteced': 'detected',
    'defination': 'definition',
    'desciption': 'description',
    'descripton': 'description',
    'desparatly': 'desperately',
    'dessigned': 'designed',
    'develope': 'develop',
    'developement': 'development',
    'diffrent': 'different',
    'dificult': 'difficult',
    'disapline': 'discipline',
    'dispair': 'despair',
    'dissappear': 'disappear',
    'dissapoint': 'disappoint',
    'dissappoint': 'disappoint',
    'distroy': 'destroy',
    'docuement': 'document',
    'documnet': 'document',
    'doesnt': "doesn't",
    'dont': "don't",
    'ealier': 'earlier',
    'easiliy': 'easily',
    'effecient': 'efficient',
    'efford': 'effort',
    'effords': 'efforts',
    'eleminated': 'eliminated',
    'eligable': 'eligible',
    'embarass': 'embarrass',
    'embarassment': 'embarrassment',
    'emergecy': 'emergency',
    'emphaised': 'emphasised',
    'emphsis': 'emphasis',
    'emploee': 'employee',
    'emploees': 'employees',
    'enchanced': 'enhanced',
    'endevor': 'endeavor',
    'enforceing': 'enforcing',
    'engagment': 'engagement',
    'engeneering': 'engineering',
    'enlargeing': 'enlarging',
    'enthusisatic': 'enthusiastic',
    'entitied': 'entitled',
    'enviroment': 'environment',
    'enviromental': 'environmental',
    'envirument': 'environment',
    'eposide': 'episode',
    'equipement': 'equipment',
    'equippment': 'equipment',
    'equivelant': 'equivalent',
    'errar': 'error',
    'errosion': 'erosion',
    'esential': 'essential',
    'espeically': 'especially',
    'essense': 'essence',
    'essestial': 'essential',
    'establisment': 'establishment',
    'exagerrate': 'exaggerate',
    'exagerrated': 'exaggerated',
    'exampel': 'example',
    'excedded': 'exceeded',
    'excelent': 'excellent',
    'excellant': 'excellent',
    'excercise': 'exercise',
    'excted': 'excited',
    'exectued': 'executed',
    'exelent': 'excellent',
    'existance': 'existence',
    'exsist': 'exist',
    'experiance': 'experience',
    'experpience': 'experience',
    'expiriment': 'experiment',
    'explanent': 'explanation',
    'explict': 'explicit',
    'extrordinary': 'extraordinary',
    'faciliy': 'facility',
    'familliar': 'familiar',
    'familar': 'familiar',
    'famouse': 'famous',
    'feasable': 'feasible',
    'firey': 'fiery',
    'flourescent': 'fluorescent',
    'folowing': 'following',
    'forhead': 'forehead',
    'foriegn': 'foreign',
    'formallly': 'formally',
    'forword': 'foreword',
    'fourties': 'forties',
    'friendhsip': 'friendship',
    'fullfil': 'fulfil',
    'fundametal': 'fundamental',
    'fundamentaly': 'fundamentally',
    'furios': 'furious',
    'furneral': 'funeral',
    'furthermore': 'furthermore',
    'futre': 'future',
    'gaurd': 'guard',
    'gaurdian': 'guardian',
    'generly': 'generally',
    'gerenate': 'generate',
    'goverment': 'government',
    'governer': 'governor',
    'govermental': 'governmental',
    'gracefull': 'graceful',
    'gradualy': 'gradually',
    'grammer': 'grammar',
    'guage': 'gauge',
    'guidence': 'guidance',
    'hasnt': "hasn't",
    'hasppy': 'happy',
    'heathy': 'healthy',
    'heighth': 'height',
    'hellp': 'help',
    'helpfull': 'helpful',
    'hesistant': 'hesitant',
    'heterogenous': 'heterogeneous',
    'hisself': 'himself',
    'historicaly': 'historically',
    'hitories': 'histories',
    'hitory': 'history',
    'hospitable': 'hospitable',
    'hould': 'hold',
    'howver': 'however',
    'hppened': 'happened',
    'humour': 'humor',
    'hvae': 'have',
    'idealogy': 'ideology',
    'ideosyncratic': 'idiosyncratic',
    'ignorrant': 'ignorant',
    'imagenary': 'imaginary',
    'imagin': 'imagine',
    'immedietly': 'immediately',
    'immeditely': 'immediately',
    'impeach': 'impeach',
    'implementtation': 'implementation',
    'impliment': 'implement',
    'importent': 'important',
    'importnat': 'important',
    'impressario': 'impresario',
    'inadvertant': 'inadvertent',
    'inadvertantly': 'inadvertently',
    'incorportae': 'incorporate',
    'incorported': 'incorporated',
    'incredable': 'incredible',
    'indefinately': 'indefinitely',
    'indepedant': 'independent',
    'indipendent': 'independent',
    'indispensible': 'indispensable',
    'individial': 'individual',
    'inevitableble': 'inevitable',
    'influance': 'influence',
    'influencial': 'influential',
    'inhabitant': 'inhabitant',
    'inheritage': 'heritage',
    'innoculate': 'inoculate',
    'innoculation': 'inoculation',
    'insistant': 'insistent',
    'insitution': 'institution',
    'inspec': 'inspect',
    'inspiration': 'inspiration',
    'instalation': 'installation',
    'instade': 'instead',
    'insted': 'instead',
    'instiution': 'institution',
    'instument': 'instrument',
    'integraly': 'integrally',
    'intelegent': 'intelligent',
    'intelled': 'intelligent',
    'intellectural': 'intellectual',
    'interuption': 'interruption',
    'intresting': 'interesting',
    'intrepid': 'intrepid',
    'invasion': 'invasion',
    'inventer': 'inventor',
    'invertibrates': 'invertebrates',
    'irregardless': 'regardless',
    'irresistable': 'irresistible',
    'irritible': 'irritable',
    'isnt': "isn't",
    'jewelery': 'jewelry',
    'judgement': 'judgment',
    'juniour': 'junior',
    'justfiy': 'justify',
    'keeped': 'kept',
    'kindom': 'kingdom',
    'knwo': 'know',
    'leran': 'learn',
    'liason': 'liaison',
    'libary': 'library',
    'librarry': 'library',
    'licence': 'license',
    'liesure': 'leisure',
    'lifetstyle': 'lifestyle',
    'littel': 'little',
    'litteral': 'literal',
    'litterally': 'literally',
    'livley': 'lively',
    'lmits': 'limits',
    'lnguage': 'language',
    'longevity': 'longevity',
    'loose': 'lose',
    'loosing': 'losing',
    'losed': 'lost',
    'lovley': 'lovely',
    'luckly': 'luckily',
    'lugage': 'luggage',
    'magasine': 'magazine',
    'magin': 'magic',
    'magnificient': 'magnificent',
    'maintainance': 'maintenance',
    'maintanance': 'maintenance',
    'maintenence': 'maintenance',
    'maintina': 'maintain',
    'majorirty': 'majority',
    'malfunc': 'malfunction',
    'managable': 'manageable',
    'managment': 'management',
    'manoeuvre': 'maneuver',
    'manufature': 'manufacture',
    'manufatured': 'manufactured',
    'manufaturing': 'manufacturing',
    'mapp': 'map',
    'margine': 'margin',
    'marraige': 'marriage',
    'mispell': 'misspell',
    'mispelled': 'misspelled',
    'mispelling': 'misspelling',
    'occured': 'occurred',
    'ocurred': 'occurred',
    'misterious': 'mysterious',
    'mistery': 'mystery',
    'mistry': 'mystery',
    'mobbile': 'mobile',
    'moderm': 'modem',
    'modle': 'model',
    'moisture': 'moisture',
    'monastary': 'monastery',
    'monitary': 'monetary',
    'motto': 'motto',
    'mould': 'mold',
    'mouldy': 'moldy',
    'mous': 'mouse',
    'moustache': 'mustache',
    'mucus': 'mucus',
    'muder': 'murder',
    'multi_media': 'multimedia',
    'mulitple': 'multiple',
    'murmer': 'murmur',
    'mythus': 'myths',
    'naive': 'naive',
    'naively': 'naively',
    'Napolean': 'Napoleon',
    'natural': 'natural',
    'nature': 'nature',
    'naturual': 'natural',
    'neccessary': 'necessary',
    'necessery': 'necessary',
    'neice': 'niece',
    'neigbourhood': 'neighbourhood',
    'neigbour': 'neighbour',
    'nervious': 'nervous',
    'newpaper': 'newspaper',
    'niche': 'niche',
    'nieghbor': 'neighbor',
    'nieghbours': 'neighbours',
    'noc': 'know',
    'noice': 'noise',
    'noone': 'no one',
    'noticable': 'noticeable',
    'noticably': 'noticeably',
    'nucus': 'mucus',
    'nuisance': 'nuisance',
    'obdurite': 'obdurate',
    'obediant': 'obedient',
    'obfus': 'obfuscate',
    'obligated': 'obligated',
    'observe': 'observe',
    'obstacal': 'obstacle',
    'ocassion': 'occasion',
    'ocassionally': 'occasionally',
    'occassion': 'occasion',
    'occassional': 'occasional',
    'occationally': 'occasionally',
    'occurrance': 'occurrence',
    'occurrances': 'occurrences',
    'ocur': 'occur',
    'offical': 'official',
    'olv': 'love',
    'omage': 'homage',
    'omission': 'omission',
    'omitted': 'omitted',
    'onery': 'onery',
    'oportunity': 'opportunity',
    'oposite': 'opposite',
    'oppen': 'open',
    'opperate': 'operate',
    'oppertunity': 'opportunity',
    'optomism': 'optimism',
    'orded': 'ordered',
    'organ': 'organ',
    'organim': 'organism',
    'organiztion': 'organization',
    'orientate': 'orient',
    'originnate': 'originate',
    'orignal': 'original',
    'other': 'other',
    'others': 'others',
    'otherwise': 'otherwise',
    'ought': 'ought',
    'outragious': 'outrageous',
    'ovre': 'over',
    'owe': 'owe',
    'pade': 'trade',
    'palate': 'palate',
    'pamflet': 'pamphlet',
    'paralell': 'parallel',
    'paralelly': 'parallelly',
    'parallely': 'parallelly',
    'parametter': 'parameter',
    'paranoya': 'paranoia',
    'parel': 'parrel',
    'parentical': 'parenthetical',
    'parit': 'party',
    'parliment': 'parliament',
    'partice': 'participate',
    'partiction': 'partition',
    'past': 'past',
    'paste': 'paste',
    'patent': 'patent',
    'patience': 'patience',
    'peace': 'peace',
    'peculure': 'peculiar',
    'peice': 'piece',
    'pelvis': 'pelvis',
    'penatrate': 'penetrate',
    'peninsula': 'peninsula',
    'pensil': 'pencil',
    'percieve': 'perceive',
    'percept': 'percept',
    'perfect': 'perfect',
    'performace': 'performance',
    'perform': 'perform',
    'perfume': 'perfume',
    'perjorative': 'pejorative',
    'permanant': 'permanent',
    'permenant': 'permanent',
    'permission': 'permission',
    'permit': 'permit',
    'peronal': 'personal',
    'perphas': 'perhaps',
    'persistant': 'persistent',
    'personel': 'personnel',
    'perspective': 'perspective',
    'perspire': 'perspire',
    'petetion': 'petition',
    'pevent': 'prevent',
    'phase': 'phase',
    'phenomenon': 'phenomenon',
    'phone': 'phone',
    'phylosophical': 'philosophical',
    'pictue': 'picture',
    'piece': 'piece',
    'pilot': 'pilot',
    'pinacle': 'pinnacle',
    'plagarism': 'plagiarism',
    'plane': 'plane',
    'platfoms': 'platforms',
    'platue': 'plateau',
    'pleadge': 'pledge',
    'pleasent': 'pleasant',
    'pleause': 'please',
    'plese': 'please',
    'plublish': 'publish',
    'pluse': 'pulse',
    'poem': 'poem',
    'poer': 'power',
    'poin': 'point',
    'pointer': 'pointer',
    'poisin': 'poison',
    'polish': 'polish',
    'polite': 'polite',
    'politicle': 'political',
    'poll': 'poll',
    'polutant': 'pollutant',
    'polute': 'pollute',
    'poluted': 'polluted',
    'ponder': 'ponder',
    'poniticale': 'pontificate',
    'poore': 'poor',
    'populare': 'popular',
    'popular': 'popular',
    'populism': 'populism',
    'pore': 'pore',
    'porpuse': 'purpose',
    'port': 'port',
    'portal': 'portal',
    'portion': 'portion',
    'portugese': 'Portuguese',
    'posess': 'possess',
    'possess': 'possess',
    'possibility': 'possibility',
    'possible': 'possible',
    'possum': 'opossum',
    'pot': 'pot',
    'potential': 'potential',
    'potentially': 'potentially',
    'poular': 'popular',
    'poularity': 'popularity',
    'pour': 'pour',
    'poverty': 'poverty',
    'power': 'power',
    'powerful': 'powerful',
    'practical': 'practical',
    'practically': 'practically',
    'practise': 'practise',
    'prairy': 'prairie',
    'prarie': 'prairie',
    'prayer': 'prayer',
    'preceed': 'precede',
    'preceeds': 'precedes',
    'preciouse': 'precious',
    'precipice': 'precipice',
    'prectice': 'practice',
    'predic': 'predict',
    'predict': 'predict',
    'prejudice': 'prejudice',
    'predomantly': 'predominantly',
    'prefered': 'preferred',
    'prefering': 'preferring',
    'priviledge': 'privilege',
    'pregancy': 'pregnancy',
    'preganant': 'pregnant',
    'pregnant': 'pregnant',
    'preliminary': 'preliminary',
    'prelude': 'prelude',
    'premature': 'premature',
    'premier': 'premier',
    'premise': 'premise',
    'premium': 'premium',
    'prepair': 'prepare',
    'prepairing': 'preparing',
    'prepairation': 'preparation',
    'prepeare': 'prepare',
    'prepearing': 'preparing',
    'preponderance': 'preponderance',
    'prerogative': 'prerogative',
    'presance': 'presence',
    'prescibed': 'prescribed',
    'prescription': 'prescription',
    'presedence': 'precedence',
    'presense': 'presence',
    'presidetal': 'presidential',
    'press': 'press',
    'pressure': 'pressure',
    'prestigious': 'prestigious',
    'presumibly': 'presumably',
    'pretection': 'protection',
    'pretty': 'pretty',
    'prevelant': 'prevalent',
    'prevent': 'prevent',
    'prevention': 'prevention',
    'previious': 'previous',
    'previous': 'previous',
    'previously': 'previously',
    'prey': 'prey',
    'priesthood': 'priesthood',
    'primarily': 'primarily',
    'primary': 'primary',
    'prime': 'prime',
    'primitive': 'primitive',
    'principal': 'principal',
    'principle': 'principle',
    'priniciple': 'principle',
    'privledge': 'privilege',
    'prize': 'prize',
    'probalby': 'probably',
    'probaly': 'probably',
    'probbably': 'probably',
    'probems': 'problems',
    'problem': 'problem',
    'probley': 'probably',
    'proccess': 'process',
    'proceed': 'proceed',
    'proceeds': 'proceeds',
    'proces': 'process',
    'process': 'process',
    'processe': 'processed',
    'processor': 'processor',
    'proclame': 'proclaimed',
    'proclaming': 'proclaiming',
    'prodcut': 'product',
    'prodcution': 'production',
    'producing': 'producing',
    'product': 'product',
    'production': 'production',
    'productive': 'productive',
    'productivity': 'productivity',
    'profesion': 'professor',
    'profesional': 'professional',
    'professer': 'professor',
    'professor': 'professor',
    'proficience': 'proficiency',
    'proficient': 'proficient',
    'profile': 'profile',
    'profitable': 'profitable',
    'profound': 'profound',
    'profusely': 'profusely',
    'program': 'program',
    'programer': 'programmer',
    'programing': 'programming',
    'programme': 'program',
    'recieve': 'receive',
    'refered': 'referred',
    'refering': 'referring',
    'referrence': 'reference',
    'seperate': 'separate',
    'progres': 'progress',
    'progress': 'progress',
    'progresive': 'progressive',
    'prohabitive': 'prohibitive',
    'projcet': 'project',
    'prokect': 'project',
    'proliferate': 'proliferate',
    'proliforate': 'proliferate',
    'prolog': 'prologue',
    'prominant': 'prominent',
    'promiscuous': 'promiscuous',
    'promissing': 'promising',
    'promote': 'promote',
    'promotion': 'promotion',
    'prompt': 'prompt',
    'pronouce': 'pronounce',
    'pronouced': 'pronounced',
    'pronouncement': 'pronouncement',
    'proof': 'proof',
    'propel': 'propel',
    'propeled': 'propelled',
    'propeling': 'propelling',
    'propensity': 'propensity',
    'proper': 'proper',
    'properally': 'properly',
    'properly': 'properly',
    'propert': 'property',
    'property': 'property',
    'prophacy': 'prophecy',
    'proponent': 'proponent',
    'proportion': 'proportion',
    'proposal': 'proposal',
    'propose': 'propose',
    'proposed': 'proposed',
    'proposes': 'proposes',
    'proposing': 'proposing',
    'propotion': 'proportion',
    'propotional': 'proportional',
    'propper': 'proper',
    'propriatary': 'proprietary',
    'propriatery': 'proprietary',
    'proprietory': 'proprietary',
    'prosecute': 'prosecute',
    'prosecution': 'prosecution',
    'prosess': 'process',
    'prosessor': 'professor',
    'prosperous': 'prosperous',
    'protect': 'protect',
    'protection': 'protection',
    'protien': 'protein',
    'protest': 'protest',
    'protocal': 'protocol',
    'protocall': 'protocol',
    'protocals': 'protocols',
    'protoplasm': 'protoplasm',
    'prototyp': 'prototype',
    'prototype': 'prototype',
    'protude': 'protrude',
    'proud': 'proud',
    'prove': 'prove',
    'proven': 'proven',
    'provide': 'provide',
    'providence': 'Providence',
    'provider': 'provider',
    'province': 'province',
    'provison': 'provision',
    'provocative': 'provocative',
    'proximate': 'proximate',
    'prudish': 'prudish',
    'prull': 'pry',
    'prune': 'prune',
    'pry': 'pry',
    'pseudo': 'pseudo',
    'pseudonym': 'pseudonym',
    'public': 'public',
    'publically': 'publicly',
    'publicly': 'publicly',
    'puchasing': 'purchasing',
    'puerile': 'puerile',
    'pump': 'pump',
    'puncuation': 'punctuation',
    'punctual': 'punctual',
    'punctuate': 'punctuate',
    'punctuation': 'punctuation',
    'pupil': 'pupil',
    'puppet': 'puppet',
    'purchase': 'purchase',
    'purchasing': 'purchasing',
    'pure': 'pure',
    'purile': 'puerile',
    'purpose': 'purpose',
    'purposed': 'purposed',
    'purposly': 'purposely',
    'purpously': 'purposely',
    'pursue': 'pursue',
    'pursuade': 'persuade',
    'pursuing': 'pursuing',
    'purveyor': 'purveyor',
    'purview': 'purview',
    'puzzle': 'puzzle',
    'quota': 'quota',
    'radical': 'radical',
    'raffle': 'raffle',
    'raise': 'raise',
    'ramification': 'ramification',
    'random': 'random',
    'rarely': 'rarely',
    'rate': 'rate',
    'rather': 'rather',
    'ratify': 'ratify',
    'ration': 'ration',
    'rationel': 'rational',
    'ravel': 'ravel',
    'reach': 'reach',
    'reacct': 'react',
    'reasearch': 'research',
    'reasin': 'reason',
    'rebel': 'rebel',
    'rebuke': 'rebuke',
    'rebuttle': 'rebuttal',
    'recall': 'recall',
    'recant': 'recant',
    'recapitulate': 'recapitulate',
    'receive': 'receive',
    'received': 'received',
    'receiver': 'receiver',
    'receiving': 'receiving',
    'recent': 'recent',
    'recently': 'recently',
    'receptacle': 'receptacle',
    'reception': 'reception',
    'receptor': 'receptor',
    'recess': 'recess',
    'recession': 'recession',
    'recipe': 'recipe',
    'recipient': 'recipient',
    'reciprocal': 'reciprocal',
    'reciprocate': 'reciprocate',
    'recital': 'recital',
    'recite': 'recite',
    'reckon': 'reckon',
    'reckless': 'reckless',
    'reclaim': 'reclaim',
    'recluse': 'recluse',
    'recognise': 'recognize',
    'recognition': 'recognition',
    'recognize': 'recognize',
    'recognizeable': 'recognizable',
    'recoil': 'recoil',
    'recollect': 'recollect',
    'recollection': 'recollection',
    'recommend': 'recommend',
    'recommendation': 'recommendation',
    'reconcile': 'reconcile',
    'reconciliation': 'reconciliation',
    'record': 'record',
    'recorder': 'recorder',
    'recording': 'recording',
    'recount': 'recount',
    'recover': 'recover',
    'recovery': 'recovery',
    'recreate': 'recreate',
    'recruit': 'recruit',
    'recruitment': 'recruitment',
    'rectangle': 'rectangle',
    'rectangular': 'rectangular',
    'rectification': 'rectification',
    'rectify': 'rectify',
    'rectitude': 'rectitude',
    'rectum': 'rectum',
    'recur': 'recur',
    'recurrence': 'recurrence',
    'recurrent': 'recurrent',
    'recurring': 'recurring',
    'recycle': 'recycle',
    'red': 'red',
    'redesign': 'redesign',
    'redirect': 'redirect',
    'rediscover': 'rediscover',
    'redistribute': 'redistribute',
    'reduce': 'reduce',
    'reduced': 'reduced',
    'reduces': 'reduces',
    'reducing': 'reducing',
    'reduction': 'reduction',
    'redundancy': 'redundancy',
    'redundant': 'redundant',
    'refer': 'refer',
    'referee': 'referee',
    'reference': 'reference',
    'referral': 'referral',
    'referred': 'referred',
    'referring': 'referring',
    'referer': 'referrer',
    'refine': 'refine',
    'refined': 'refined',
    'reflection': 'reflection',
    'reform': 'reform',
    'reformation': 'reformation',
    'refract': 'refract',
    'refrain': 'refrain',
    'refresh': 'refresh',
    'refugee': 'refugee',
    'refund': 'refund',
    'refurbish': 'refurbish',
    'refusal': 'refusal',
    'refuse': 'refuse',
    'regain': 'regain',
    'regal': 'regal',
    'regard': 'regard',
    'regatta': 'regatta',
    'regency': 'regency',
    'regent': 'regent',
    'regime': 'regime',
    'regimen': 'regimen',
    'region': 'region',
    'regional': 'regional',
    'register': 'register',
    'registrar': 'registrar',
    'registration': 'registration',
    'registry': 'registry',
    'regret': 'regret',
    'regular': 'regular',
    'regularly': 'regularly',
    'regulate': 'regulate',
    'regulation': 'regulation',
    'regulatory': 'regulatory',
    'rehab': 'rehab',
    'rehabilitation': 'rehabilitation',
    'rehash': 'rehash',
    'rehearsal': 'rehearsal',
    'rehearse': 'rehearse',
    'reign': 'reign',
    'reimburse': 'reimburse',
    'reinstall': 'reinstall',
    'reinstate': 'reinstate',
    'reiterate': 'reiterate',
    'reject': 'reject',
    'rejection': 'rejection',
    'rejoice': 'rejoice',
    'relate': 'relate',
    'related': 'related',
    'relation': 'relation',
    'relationship': 'relationship',
    'relative': 'relative',
    'relatively': 'relatively',
    'relax': 'relax',
    'relay': 'relay',
    'release': 'release',
    'relegate': 'relegate',
    'relent': 'relent',
    'relentless': 'relentless',
    'relevant': 'relevant',
    'reliability': 'reliability',
    'reliable': 'reliable',
    'reliance': 'reliance',
    'reliant': 'reliant',
    'relief': 'relief',
    'relieve': 'relieve',
    'religion': 'religion',
    'religious': 'religious',
    'relocate': 'relocate',
    'reluctance': 'reluctance',
    'reluctant': 'reluctant',
    'rely': 'rely',
    'remain': 'remain',
    'remainder': 'remainder',
    'remaining': 'remaining',
    'remains': 'remains',
    'remark': 'remark',
    'remarkable': 'remarkable',
    'remedy': 'remedy',
    'remember': 'remember',
    'remembrance': 'remembrance',
    'remind': 'remind',
    'reminder': 'reminder',
    'remonstrate': 'remonstrate',
    'remorse': 'remorse',
    'remote': 'remote',
    'removal': 'removal',
    'remove': 'remove',
    'rename': 'rename',
    'render': 'render',
    'rendezvous': 'rendezvous',
    'renew': 'renew',
    'renewable': 'renewable',
    'renewal': 'renewal',
    'renounce': 'renounce',
    'renovate': 'renovate',
    'renovation': 'renovation',
    'renown': 'renown',
    'renowned': 'renowned',
    'rent': 'rent',
    'rental': 'rental',
    'reorganize': 'reorganize',
    'repair': 'repair',
    'repatriate': 'repatriate',
    'repay': 'repay',
    'repeal': 'repeal',
    'repeat': 'repeat',
    'repeatedly': 'repeatedly',
    'repel': 'repel',
    'repent': 'repent',
    'repetition': 'repetition',
    'replace': 'replace',
    'replacement': 'replacement',
    'replay': 'replay',
    'replenish': 'replenish',
    'reply': 'reply',
    'report': 'report',
    'reporter': 'reporter',
    'represent': 'represent',
    'representation': 'representation',
    'representative': 'representative',
    'repress': 'repress',
    'repression': 'repression',
    'repressive': 'repressive',
    'reprieve': 'reprieve',
    'reprisal': 'reprisal',
    'reproach': 'reproach',
    'reproduce': 'reproduce',
    'reproduction': 'reproduction',
    'reproductive': 'reproductive',
    'reproof': 'reproof',
    'reprove': 'reprove',
    'reptile': 'reptile',
    'republic': 'republic',
    'repudiate': 'repudiate',
    'repugnant': 'repugnant',
    'repulse': 'repulse',
    'repulsion': 'repulsion',
    'repulsive': 'repulsive',
    'reputation': 'reputation',
    'request': 'request',
    'requiem': 'requiem',
    'require': 'require',
    'required': 'required',
    'requirement': 'requirement',
    'requisite': 'requisite',
    'rescue': 'rescue',
    'research': 'research',
    'researcher': 'researcher',
    'resell': 'resell',
    'resemble': 'resemble',
    'resent': 'resent',
    'reservation': 'reservation',
    'reserve': 'reserve',
    'reserved': 'reserved',
    'reservoir': 'reservoir',
    'reset': 'reset',
    'reside': 'reside',
    'residence': 'residence',
    'resident': 'resident',
    'residential': 'residential',
    'residual': 'residual',
    'residue': 'residue',
    'resign': 'resign',
    'resignation': 'resignation',
    'resilience': 'resilience',
    'resilient': 'resilient',
    'resist': 'resist',
    'resistance': 'resistance',
    'resolution': 'resolution',
    'resolve': 'resolve',
    'resonance': 'resonance',
    'resort': 'resort',
    'resource': 'resource',
    'respect': 'respect',
    'respectable': 'respectable',
    'respectful': 'respectful',
    'respecting': 'respecting',
    'respective': 'respective',
    'respectively': 'respectively',
    'respond': 'respond',
    'respondent': 'respondent',
    'response': 'response',
    'responsibility': 'responsibility',
    'responsible': 'responsible',
    'responsive': 'responsive',
    'rest': 'rest',
    'restart': 'restart',
    'restate': 'restate',
    'restaurant': 'restaurant',
    'restitution': 'restitution',
    'restless': 'restless',
    'restoration': 'restoration',
    'restore': 'restore',
    'restrain': 'restrain',
    'restraint': 'restraint',
    'restrict': 'restrict',
    'restriction': 'restriction',
    'restructure': 'restructure',
    'result': 'result',
    'resultant': 'resultant',
    'resume': 'resume',
    'retail': 'retail',
    'retain': 'retain',
    'retake': 'retake',
    'retaliate': 'retaliate',
    'retaliation': 'retaliation',
    'retard': 'retard',
    'retention': 'retention',
    'reticent': 'reticent',
    'retire': 'retire',
    'retirement': 'retirement',
    'retort': 'retort',
    'retouch': 'retouch',
    'retrace': 'retrace',
    'retract': 'retract',
    'retreat': 'retreat',
    'retrench': 'retrench',
    'retribution': 'retribution',
    'retrieve': 'retrieve',
    'retroactive': 'retroactive',
    'retrograde': 'retrograde',
    'retrospective': 'retrospective',
    'return': 'return',
    'reveal': 'reveal',
    'revelation': 'revelation',
    'revenge': 'revenge',
    'revenue': 'revenue',
    'reverence': 'reverence',
    'reverent': 'reverent',
    'reverse': 'reverse',
    'reversible': 'reversible',
    'revert': 'revert',
    'review': 'review',
    'reviewer': 'reviewer',
    'revise': 'revise',
    'revision': 'revision',
    'revisit': 'revisit',
    'revival': 'revival',
    'revive': 'revive',
    'revoke': 'revoke',
    'revolt': 'revolt',
    'revolution': 'revolution',
    'revolutionary': 'revolutionary',
    'revolve': 'revolve',
    'reward': 'reward',
    'rhetoric': 'rhetoric',
    'rhetorical': 'rhetorical',
    'rhyme': 'rhyme',
    'rhythm': 'rhythm',
    'rid': 'rid',
    'riddle': 'riddle',
    'ride': 'ride',
    'rider': 'rider',
    'ridge': 'ridge',
    'ridicule': 'ridicule',
    'ridiculous': 'ridiculous',
    'right': 'right',
    'righteous': 'righteous',
    'rigid': 'rigid',
    'rigorous': 'rigorous',
    'rim': 'rim',
    'rind': 'rind',
    'ring': 'ring',
    'rinse': 'rinse',
    'riot': 'riot',
    'ripe': 'ripe',
    'ripple': 'ripple',
    'rise': 'rise',
    'risk': 'risk',
    'risky': 'risky',
    'rite': 'rite',
    'ritual': 'ritual',
    'rival': 'rival',
    'rivalry': 'rivalry',
    'river': 'river',
    'rivet': 'rivet',
    'road': 'road',
    'roam': 'roam',
    'roar': 'roar',
    'roast': 'roast',
    'rob': 'rob',
    'robbery': 'robbery',
    'robe': 'robe',
    'robot': 'robot',
    'robust': 'robust',
    'rock': 'rock',
    'rocket': 'rocket',
    'rod': 'rod',
    'rode': 'ride',
    'rodent': 'rodent',
    'role': 'role',
    'roll': 'roll',
    'roller': 'roller',
    'romance': 'romance',
    'romantic': 'romantic',
    'roof': 'roof',
    'room': 'room',
    'root': 'root',
    'rope': 'rope',
    'rose': 'rose',
    'rot': 'rot',
    'rotate': 'rotate',
    'rotor': 'rotor',
    'rotten': 'rotten',
    'rough': 'rough',
    'roughly': 'roughly',
    'round': 'round',
    'route': 'route',
    'routine': 'routine',
    'rove': 'rove',
    'row': 'row',
    'royal': 'royal',
    'royalty': 'royalty',
    'rub': 'rub',
    'rubber': 'rubber',
    'rubble': 'rubble',
    'ruby': 'ruby',
    'rude': 'rude',
    'ruffle': 'ruffle',
    'rugged': 'rugged',
    'ruin': 'ruin',
    'rule': 'rule',
    'ruler': 'ruler',
    'rumor': 'rumor',
    'run': 'run',
    'runway': 'runway',
    'rural': 'rural',
    'rush': 'rush',
    'rust': 'rust',
    'rustic': 'rustic',
    'sacrifice': 'sacrifice',
    'sacrilege': 'sacrilege',
    'safe': 'safe',
    'safeguard': 'safeguard',
    'safely': 'safely',
    'safety': 'safety',
    'sage': 'sage',
    'said': 'said',
    'sail': 'sail',
    'sailor': 'sailor',
    'saint': 'saint',
    'sake': 'sake',
    'salary': 'salary',
    'sale': 'sale',
    'salient': 'salient',
    'saliva': 'saliva',
    'salmon': 'salmon',
    'salon': 'salon',
    'salt': 'salt',
    'salty': 'salty',
    'salute': 'salute',
    'salvation': 'salvation',
    'same': 'same',
    'sample': 'sample',
    'sanction': 'sanction',
    'sanctuary': 'sanctuary',
    'sand': 'sand',
    'sandal': 'sandal',
    'sane': 'sane',
    'sang': 'sing',
    'sank': 'sink',
    'sarcasm': 'sarcasm',
    'sarcastic': 'sarcastic',
    'sat': 'sit',
    'satin': 'satin',
    'satire': 'satire',
    'satisfaction': 'satisfaction',
    'satisfy': 'satisfy',
    'saturate': 'saturate',
    'sauce': 'sauce',
    'saucer': 'saucer',
    'sauna': 'sauna',
    'savage': 'savage',
    'save': 'save',
    'saving': 'saving',
    'saw': 'see',
    'say': 'say',
    'scale': 'scale',
    'scan': 'scan',
    'scandal': 'scandal',
    'scarce': 'scarce',
    'scare': 'scare',
    'scared': 'scared',
    'scarf': 'scarf',
    'scary': 'scary',
    'scatter': 'scatter',
    'scenario': 'scenario',
    'scene': 'scene',
    'scenery': 'scenery',
    'scent': 'scent',
    'scheme': 'scheme',
    'scholar': 'scholar',
    'scholarship': 'scholarship',
    'school': 'school',
    'science': 'science',
    'scientific': 'scientific',
    'scientist': 'scientist',
    'scold': 'scold',
    'scoop': 'scoop',
    'scope': 'scope',
    'scorch': 'scorch',
    'score': 'score',
    'scorn': 'scorn',
    'scout': 'scout',
    'scowl': 'scowl',
    'scramble': 'scramble',
    'scrap': 'scrap',
    'scrape': 'scrape',
    'scratch': 'scratch',
    'scrawl': 'scrawl',
    'scream': 'scream',
    'screen': 'screen',
    'screw': 'screw',
    'script': 'script',
    'scroll': 'scroll',
    'scrub': 'scrub',
    'scum': 'scum',
    'sea': 'sea',
    'seal': 'seal',
    'seam': 'seam',
    'search': 'search',
    'season': 'season',
    'seat': 'seat',
    'second': 'second',
    'secondary': 'secondary',
    'secret': 'secret',
    'secretary': 'secretary',
    'section': 'section',
    'sector': 'sector',
    'secure': 'secure',
    'security': 'security',
    'sediment': 'sediment',
    'see': 'see',
    'seed': 'seed',
    'seek': 'seek',
    'seem': 'seem',
    'seen': 'see',
    'seep': 'seep',
    'segment': 'segment',
    'seize': 'seize',
    'seizure': 'seizure',
    'seldom': 'seldom',
    'select': 'select',
    'selection': 'selection',
    'selfish': 'selfish',
    'sell': 'sell',
    'seller': 'seller',
    'semi': 'semi',
    'senate': 'senate',
    'senator': 'senator',
    'send': 'send',
    'sender': 'sender',
    'senior': 'senior',
    'sense': 'sense',
    'sensible': 'sensible',
    'sensetivity': 'sensitivity',
    'sensitivty': 'sensitivity',
    'sensitive': 'sensitive',
    'sentence': 'sentence',
    'sentiment': 'sentiment',
    'separate': 'separate',
    'sequence': 'sequence',
    'serene': 'serene',
    'serial': 'serial',
    'series': 'series',
    'sermon': 'sermon',
    'serpent': 'serpent',
    'servant': 'servant',
    'serve': 'serve',
    'server': 'server',
    'service': 'service',
    'session': 'session',
    'set': 'set',
    'setting': 'setting',
    'settle': 'settle',
    'settlement': 'settlement',
    'severe': 'severe',
    'shackle': 'shackle',
    'shade': 'shade',
    'shadow': 'shadow',
    'shaft': 'shaft',
    'shake': 'shake',
    'shaken': 'shaken',
    'shaky': 'shaky',
    'shall': 'shall',
    'shallow': 'shallow',
    'shame': 'shame',
    'shape': 'shape',
    'share': 'share',
    'shark': 'shark',
    'sharp': 'sharp',
    'shatter': 'shatter',
    'shave': 'shave',
    'shed': 'shed',
    'sheer': 'sheer',
    'sheet': 'sheet',
    'shelf': 'shelf',
    'shell': 'shell',
    'shelter': 'shelter',
    'shift': 'shift',
    'shine': 'shine',
    'shiny': 'shiny',
    'ship': 'ship',
    'shipment': 'shipment',
    'shock': 'shock',
    'shoe': 'shoe',
    'shook': 'shake',
    'shoot': 'shoot',
    'shop': 'shop',
    'shore': 'shore',
    'short': 'short',
    'shortage': 'shortage',
    'shortly': 'shortly',
    'shot': 'shot',
    'should': 'should',
    'shoulder': 'shoulder',
    'shout': 'shout',
    'shove': 'shove',
    'shovel': 'shovel',
    'show': 'show',
    'shower': 'shower',
    'shrewd': 'shrewd',
    'shriek': 'shriek',
    'shrink': 'shrink',
    'shroud': 'shroud',
    'shrug': 'shrug',
    'shrunk': 'shrink',
    'shudder': 'shudder',
    'shuffle': 'shuffle',
    'shun': 'shun',
    'shut': 'shut',
    'shutter': 'shutter',
    'shuttle': 'shuttle',
    'sibling': 'sibling',
    'sick': 'sick',
    'side': 'side',
    'siege': 'siege',
    'sieve': 'sieve',
    'sigh': 'sigh',
    'sight': 'sight',
    'sign': 'sign',
    'signal': 'signal',
    'signature': 'signature',
    'significance': 'significance',
    'significant': 'significant',
    'silence': 'silence',
    'silent': 'silent',
    'silhouette': 'silhouette',
    'silk': 'silk',
    'silly': 'silly',
    'silver': 'silver',
    'similar': 'similar',
    'similarly': 'similarly',
    'simple': 'simple',
    'simplify': 'simplify',
    'simply': 'simply',
    'simulate': 'simulate',
    'simultaneous': 'simultaneous',
    'since': 'since',
    'sincere': 'sincere',
    'sinecure': 'sinecure',
    'sing': 'sing',
    'singe': 'singe',
    'singer': 'singer',
    'single': 'single',
    'sink': 'sink',
    'sinuous': 'sinuous',
    'sir': 'sir',
    'siren': 'siren',
    'sister': 'sister',
    'sit': 'sit',
    'site': 'site',
    'situation': 'situation',
    'six': 'six',
    'size': 'size',
    'skate': 'skate',
    'skeleton': 'skeleton',
    'sketch': 'sketch',
    'sketchy': 'sketchy',
    'skill': 'skill',
    'skilled': 'skilled',
    'skim': 'skim',
    'skin': 'skin',
    'skip': 'skip',
    'skirt': 'skirt',
    'skull': 'skull',
    'slab': 'slab',
    'slack': 'slack',
    'slam': 'slam',
    'slander': 'slander',
    'slang': 'slang',
    'slant': 'slant',
    'slap': 'slap',
    'slash': 'slash',
    'slate': 'slate',
    'slaughter': 'slaughter',
    'slave': 'slave',
    'slavery': 'slavery',
    'slay': 'slay',
    'sleazy': 'sleazy',
    'sleek': 'sleek',
    'sleep': 'sleep',
    'sleepy': 'sleepy',
    'sleeve': 'sleeve',
    'slender': 'slender',
    'slice': 'slice',
    'slick': 'slick',
    'slide': 'slide',
    'slight': 'slight',
    'slim': 'slim',
    'slime': 'slime',
    'slimy': 'slimy',
    'sling': 'sling',
    'slip': 'slip',
    'slit': 'slit',
    'sliver': 'sliver',
    'slogan': 'slogan',
    'slope': 'slope',
    'sloppy': 'sloppy',
    'slot': 'slot',
    'slow': 'slow',
    'slowly': 'slowly',
    'slug': 'slug',
    'slum': 'slum',
    'slump': 'slump',
    'slur': 'slur',
    'slush': 'slush',
    'sly': 'sly',
    'smack': 'smack',
    'small': 'small',
    'smart': 'smart',
    'smash': 'smash',
    'smear': 'smear',
    'smell': 'smell',
    'smile': 'smile',
    'smirk': 'smirk',
    'smith': 'smith',
    'smog': 'smog',
    'smoke': 'smoke',
    'smooth': 'smooth',
    'smother': 'smother',
    'smudge': 'smudge',
    'smuggle': 'smuggle',
    'snack': 'snack',
    'snag': 'snag',
    'snail': 'snail',
    'snake': 'snake',
    'snap': 'snap',
    'snare': 'snare',
    'snarl': 'snarl',
    'snatch': 'snatch',
    'sneak': 'sneak',
    'sneaky': 'sneaky',
    'sneer': 'sneer',
    'sneeze': 'sneeze',
    'snicker': 'snicker',
    'sniff': 'sniff',
    'snip': 'snip',
    'snipe': 'snipe',
    'sniper': 'sniper',
    'snob': 'snob',
    'snoop': 'snoop',
    'snooze': 'snooze',
    'snore': 'snore',
    'snort': 'snort',
    'snout': 'snout',
    'snow': 'snow',
    'snowy': 'snowy',
    'snub': 'snub',
    'snuff': 'snuff',
    'snug': 'snug',
    'so': 'so',
    'soak': 'soak',
    'soap': 'soap',
    'soar': 'soar',
    'sob': 'sob',
    'sober': 'sober',
    'soccer': 'soccer',
    'social': 'social',
    'society': 'society',
    'sock': 'sock',
    'socket': 'socket',
    'soda': 'soda',
    'sofa': 'sofa',
    'soft': 'soft',
    'soften': 'soften',
    'software': 'software',
    'soil': 'soil',
    'solar': 'solar',
    'sold': 'sell',
    'soldier': 'soldier',
    'sole': 'sole',
    'solely': 'solely',
    'solemn': 'solemn',
    'solid': 'solid',
    'solidarity': 'solidarity',
    'solitary': 'solitary',
    'solo': 'solo',
    'solution': 'solution',
    'solve': 'solve',
    'somber': 'somber',
    'some': 'some',
    'somebody': 'somebody',
    'somehow': 'somehow',
    'someone': 'someone',
    'something': 'something',
    'sometime': 'sometime',
    'somewhat': 'somewhat',
    'somewhere': 'somewhere',
    'son': 'son',
    'sonar': 'sonar',
    'song': 'song',
    'soon': 'soon',
    'soot': 'soot',
    'soothe': 'soothe',
    'sophisticated': 'sophisticated',
    'sore': 'sore',
    'sorrow': 'sorrow',
    'sorry': 'sorry',
    'sort': 'sort',
    'sought': 'seek',
    'soul': 'soul',
    'sound': 'sound',
    'soup': 'soup',
    'sour': 'sour',
    'source': 'source',
    'south': 'south',
    'southern': 'southern',
    'sovereign': 'sovereign',
    'soviet': 'Soviet',
    'sow': 'sow',
    'space': 'space',
    'spacious': 'spacious',
    'spade': 'spade',
    'span': 'span',
    'spare': 'spare',
    'spark': 'spark',
    'sparrow': 'sparrow',
    'sparse': 'sparse',
    'spasm': 'spasm',
    'spawn': 'spawn',
    'speak': 'speak',
    'speaker': 'speaker',
    'spear': 'spear',
    'special': 'special',
    'specialist': 'specialist',
    'specialize': 'specialize',
    'species': 'species',
    'specific': 'specific',
    'specification': 'specification',
    'specify': 'specify',
    'specimen': 'specimen',
    'spectacle': 'spectacle',
    'spectacular': 'spectacular',
    'spectator': 'spectator',
    'spectrum': 'spectrum',
    'speculation': 'speculation',
    'speech': 'speech',
    'speed': 'speed',
    'speedy': 'speedy',
    'spell': 'spell',
    'spelling': 'spelling',
    'tecnical': 'technical',
    'spend': 'spend',
    'spent': 'spend',
    'sphere': 'sphere',
    'spice': 'spice',
    'spicy': 'spicy',
    'spider': 'spider',
    'spike': 'spike',
    'spill': 'spill',
    'spin': 'spin',
    'spine': 'spine',
    'spiral': 'spiral',
    'spirit': 'spirit',
    'spiritual': 'spiritual',
    'spit': 'spit',
    'spite': 'spite',
    'splash': 'splash',
    'splendid': 'splendid',
    'splice': 'splice',
    'split': 'split',
    'spoil': 'spoil',
    'spoke': 'speak',
    'spoken': 'speak',
    'sponge': 'sponge',
    'sponsor': 'sponsor',
    'spontaneous': 'spontaneous',
    'spoon': 'spoon',
    'sport': 'sport',
    'spot': 'spot',
    'spotless': 'spotless',
    'spouse': 'spouse',
    'spout': 'spout',
    'sprawl': 'sprawl',
    'spray': 'spray',
    'spread': 'spread',
    'spring': 'spring',
    'sprint': 'sprint',
    'sprout': 'sprout',
    'spruce': 'spruce',
    'sprung': 'spring',
    'spud': 'spud',
    'spun': 'spin',
    'spur': 'spur',
    'spurious': 'spurious',
    'spurt': 'spurt',
    'spy': 'spy',
    'squad': 'squad',
    'square': 'square',
    'squash': 'squash',
    'squat': 'squat',
    'squeak': 'squeak',
    'squeaky': 'squeaky',
    'squeal': 'squeal',
    'squeeze': 'squeeze',
    'squid': 'squid',
    'stab': 'stab',
    'stability': 'stability',
    'stable': 'stable',
    'stack': 'stack',
    'staff': 'staff',
    'stage': 'stage',
    'stagger': 'stagger',
    'stagnant': 'stagnant',
    'stagnate': 'stagnate',
    'stain': 'stain',
    'stair': 'stair',
    'staircase': 'staircase',
    'stake': 'stake',
    'stale': 'stale',
    'stalk': 'stalk',
    'stall': 'stall',
    'stamp': 'stamp',
    'stance': 'stance',
    'stand': 'stand',
    'standard': 'standard',
    'standing': 'standing',
    'staple': 'staple',
    'star': 'star',
    'starch': 'starch',
    'stare': 'stare',
    'stark': 'stark',
    'start': 'start',
    'startle': 'startle',
    'starvation': 'starvation',
    'starve': 'starve',
    'state': 'state',
    'statement': 'statement',
    'station': 'station',
    'stationary': 'stationary',
    'stationery': 'stationery',
    'statistic': 'statistic',
    'statue': 'statue',
    'status': 'status',
    'statute': 'statute',
    'steady': 'steady',
    'steak': 'steak',
    'steal': 'steal',
    'stealth': 'stealth',
    'steam': 'steam',
    'steel': 'steel',
    'steep': 'steep',
    'steer': 'steer',
    'stem': 'stem',
    'step': 'step',
    'stew': 'stew',
    'steward': 'steward',
    'stick': 'stick',
    'sticky': 'sticky',
    'stiff': 'stiff',
    'stifle': 'stifle',
    'still': 'still',
    'sting': 'sting',
    'stingy': 'stingy',
    'stink': 'stink',
    'stir': 'stir',
    'stitch': 'stitch',
    'stock': 'stock',
    'stoke': 'stoke',
    'stole': 'steal',
    'stolen': 'steal',
    'stomp': 'stomp',
    'stone': 'stone',
    'stony': 'stony',
    'stood': 'stand',
    'stool': 'stool',
    'stoop': 'stoop',
    'stop': 'stop',
    'store': 'store',
    'storm': 'storm',
    'story': 'story',
    'stout': 'stout',
    'stove': 'stove',
    'straight': 'straight',
    'straighten': 'straighten',
    'strain': 'strain',
    'strand': 'strand',
    'strange': 'strange',
    'stranger': 'stranger',
    'strangle': 'strangle',
    'strap': 'strap',
    'strategy': 'strategy',
    'straw': 'straw',
    'stray': 'stray',
    'streak': 'streak',
    'stream': 'stream',
    'street': 'street',
    'strength': 'strength',
    'strengthen': 'strengthen',
    'stress': 'stress',
    'stretch': 'stretch',
    'strict': 'strict',
    'stride': 'stride',
    'strife': 'strife',
    'strike': 'strike',
    'striking': 'striking',
    'string': 'string',
    'strip': 'strip',
    'stripe': 'stripe',
    'strive': 'strive',
    'stroke': 'stroke',
    'stroll': 'stroll',
    'strong': 'strong',
    'strongly': 'strongly',
    'struck': 'strike',
    'structure': 'structure',
    'struggle': 'struggle',
    'strung': 'string',
    'strut': 'strut',
    'stub': 'stub',
    'stubborn': 'stubborn',
    'stuck': 'stick',
    'student': 'student',
    'studio': 'studio',
    'study': 'study',
    'stuff': 'stuff',
    'stumble': 'stumble',
    'stump': 'stump',
    'stun': 'stun',
    'stung': 'sting',
    'stunk': 'stink',
    'stunning': 'stunning',
    'stunt': 'stunt',
    'stupid': 'stupid',
    'sturdy': 'sturdy',
    'style': 'style',
    'subject': 'subject',
    'submit': 'submit',
    'subordinate': 'subordinate',
    'subscribe': 'subscribe',
    'subsequent': 'subsequent',
    'subside': 'subside',
    'substance': 'substance',
    'substantial': 'substantial',
    'substitute': 'substitute',
    'subtitle': 'subtitle',
    'subtle': 'subtle',
    'suburb': 'suburb',
    'succeed': 'succeed',
    'success': 'success',
    'successful': 'successful',
    'such': 'such',
    'suck': 'suck',
    'sudden': 'sudden',
    'suddenly': 'suddenly',
    'sue': 'sue',
    'suffer': 'suffer',
    'sufficient': 'sufficient',
    'sugar': 'sugar',
    'suggest': 'suggest',
    'suggestion': 'suggestion',
    'suicide': 'suicide',
    'suit': 'suit',
    'suitable': 'suitable',
    'suitcase': 'suitcase',
    'suite': 'suite',
    'suitor': 'suitor',
    'sulk': 'sulk',
    'sultan': 'Sultan',
    'sum': 'sum',
    'summary': 'summary',
    'summer': 'summer',
    'summit': 'summit',
    'summon': 'summon',
    'sun': 'sun',
    'sundae': 'sundae',
    'sunday': 'Sunday',
    'sung': 'sing',
    'sunk': 'sink',
    'sunlight': 'sunlight',
    'sunny': 'sunny',
    'super': 'super',
    'superb': 'superb',
    'superficial': 'superficial',
    'superfluous': 'superfluous',
    'superintendent': 'superintendent',
    'superior': 'superior',
    'supermarket': 'supermarket',
    'supernatural': 'supernatural',
    'supervise': 'supervise',
    'supper': 'supper',
    'supplement': 'supplement',
    'supply': 'supply',
    'support': 'support',
    'supporter': 'supporter',
    'suppose': 'suppose',
    'supposed': 'supposed',
    'suppress': 'suppress',
    'supreme': 'supreme',
    'sure': 'sure',
    'surely': 'surely',
    'surf': 'surf',
    'surface': 'surface',
    'surfeit': 'surfeit',
    'surge': 'surge',
    'surgeon': 'surgeon',
    'surgery': 'surgery',
    'surplus': 'surplus',
    'surprise': 'surprise',
    'surprised': 'surprised',
    'surprising': 'surprising',
    'surreal': 'surreal',
    'surrender': 'surrender',
    'surround': 'surround',
    'surrounding': 'surrounding',
    'survey': 'survey',
    'survival': 'survival',
    'survive': 'survive',
    'survivor': 'survivor',
    'suspect': 'suspect',
    'suspend': 'suspend',
    'suspense': 'suspense',
    'suspicion': 'suspicion',
    'suspicious': 'suspicious',
    'sustain': 'sustain',
    'swab': 'swab',
    'swam': 'swim',
    'swamp': 'swamp',
    'swan': 'swan',
    'swap': 'swap',
    'swarm': 'swarm',
    'swat': 'swat',
    'sway': 'sway',
    'swear': 'swear',
    'sweat': 'sweat',
    'sweater': 'sweater',
    'sweep': 'sweep',
    'sweet': 'sweet',
    'swell': 'swell',
    'swept': 'sweep',
    'swift': 'swift',
    'swim': 'swim',
    'swindle': 'swindle',
    'swine': 'swine',
    'swing': 'swing',
    'swipe': 'swipe',
    'swirl': 'swirl',
    'switch': 'switch',
    'swollen': 'swell',
    'swoon': 'swoon',
    'swoop': 'swoop',
    'sword': 'sword',
    'swore': 'swear',
    'sworn': 'swear',
    'swum': 'swim',
    'swung': 'swing',
    'syllable': 'syllable',
    'symbol': 'symbol',
    'symbolic': 'symbolic',
    'symmetry': 'symmetry',
    'sympathetic': 'sympathetic',
    'sympathy': 'sympathy',
    'symphony': 'symphony',
    'symptom': 'symptom',
    'syndrome': 'syndrome',
    'synonym': 'synonym',
    'syntax': 'syntax',
    'synthesis': 'synthesis',
    'system': 'system',
    'systematic': 'systematic',
    'table': 'table',
    'tablet': 'tablet',
    'taboo': 'taboo',
    'tacit': 'tacit',
    'tack': 'tack',
    'tackle': 'tackle',
    'tact': 'tact',
    'tactful': 'tactful',
    'tactic': 'tactic',
    'tactics': 'tactics',
    'tail': 'tail',
    'tailor': 'tailor',
    'taint': 'taint',
    'take': 'take',
    'taken': 'take',
    'tale': 'tale',
    'talent': 'talent',
    'talented': 'talented',
    'talk': 'talk',
    'tall': 'tall',
    'tally': 'tally',
    'tame': 'tame',
    'tamper': 'tamper',
    'tan': 'tan',
    'tang': 'tang',
    'tangible': 'tangible',
    'tangle': 'tangle',
    'tank': 'tank',
    'tanker': 'tanker',
    'tap': 'tap',
    'tape': 'tape',
    'target': 'target',
    'tariff': 'tariff',
    'tarnish': 'tarnish',
    'task': 'task',
    'taste': 'taste',
    'tasteless': 'tasteless',
    'tasty': 'tasty',
    'taught': 'teach',
    'taunt': 'taunt',
    'taut': 'taut',
    'tavern': 'tavern',
    'tax': 'tax',
    'taxi': 'taxi',
    'taxpayer': 'taxpayer',
    'tea': 'tea',
    'teach': 'teach',
    'teacher': 'teacher',
    'teaching': 'teaching',
    'team': 'team',
    'teammate': 'teammate',
    'teamwork': 'teamwork',
    'tear': 'tear',
    'tease': 'tease',
    'technical': 'technical',
    'technically': 'technically',
    'technique': 'technique',
    'technology': 'technology',
    'tedious': 'tedious',
    'teenage': 'teenage',
    'teenager': 'teenager',
    'teens': 'teens',
    'teeth': 'teeth',
    'telegram': 'telegram',
    'telephone': 'telephone',
    'television': 'television',
    'tell': 'tell',
    'temper': 'temper',
    'temperature': 'temperature',
    'temple': 'temple',
    'tempo': 'tempo',
    'temporal': 'temporal',
    'temporary': 'temporary',
    'tempt': 'tempt',
    'temptation': 'temptation',
    'ten': 'ten',
    'tenant': 'tenant',
    'tend': 'tend',
    'tendency': 'tendency',
    'tender': 'tender',
    'tennis': 'tennis',
    'tense': 'tense',
    'tension': 'tension',
    'tent': 'tent',
    'tentative': 'tentative',
    'tenth': 'tenth',
    'tenure': 'tenure',
    'term': 'term',
    'terminal': 'terminal',
    'terminate': 'terminate',
    'terrain': 'terrain',
    'terrible': 'terrible',
    'terrific': 'terrific',
    'territory': 'territory',
    'terror': 'terror',
    'test': 'test',
    'testify': 'testify',
    'testimony': 'testimony',
    'text': 'text',
    'textbook': 'textbook',
    'texture': 'texture',
    'than': 'than',
    'thank': 'thank',
    'thanksgiving': 'Thanksgiving',
    'that': 'that',
    'theater': 'theater',
    'theft': 'theft',
    'their': 'their',
    'theirs': 'theirs',
    'them': 'them',
    'theme': 'theme',
    'themselves': 'themselves',
    'then': 'then',
    'theorem': 'theorem',
    'theory': 'theory',
    'therapy': 'therapy',
    'there': 'there',
    'thereafter': 'thereafter',
    'therefore': 'therefore',
    'thermal': 'thermal',
    'thermometer': 'thermometer',
    'these': 'these',
    'thesis': 'thesis',
    'they': 'they',
    'thick': 'thick',
    'thicken': 'thicken',
    'thickness': 'thickness',
    'thief': 'thief',
    'thigh': 'thigh',
    'thin': 'thin',
    'thing': 'thing',
    'think': 'think',
    'third': 'third',
    'thirst': 'thirst',
    'thirsty': 'thirsty',
    'thirteen': 'thirteen',
    'thirty': 'thirty',
    'this': 'this',
    'thorn': 'thorn',
    'thorough': 'thorough',
    'those': 'those',
    'though': 'though',
    'thought': 'thought',
    'thousand': 'thousand',
    'thread': 'thread',
    'threat': 'threat',
    'threaten': 'threaten',
    'three': 'three',
    'threshold': 'threshold',
    'threw': 'throw',
    'thrift': 'thrift',
    'thrifty': 'thrifty',
    'thrill': 'thrill',
    'thriller': 'thriller',
    'thrive': 'thrive',
    'throat': 'throat',
    'throne': 'throne',
    'throng': 'throng',
    'through': 'through',
    'throughout': 'throughout',
    'throw': 'throw',
    'thrust': 'thrust',
    'thug': 'thug',
    'thumb': 'thumb',
    'thunder': 'thunder',
    'thus': 'thus',
    'thwart': 'thwart',
    'tick': 'tick',
    'ticket': 'ticket',
    'tickle': 'tickle',
    'tidal': 'tidal',
    'tide': 'tide',
    'tidy': 'tidy',
    'tie': 'tie',
    'tier': 'tier',
    'tiger': 'tiger',
    'tight': 'tight',
    'tile': 'tile',
    'till': 'till',
    'tilt': 'tilt',
    'timber': 'timber',
    'time': 'time',
    'timely': 'timely',
    'timer': 'timer',
    'timid': 'timid',
    'tin': 'tin',
    'tinge': 'tinge',
    'tingle': 'tingle',
    'tint': 'tint',
    'tiny': 'tiny',
    'tip': 'tip',
    'tire': 'tire',
    'tired': 'tired',
    'tissue': 'tissue',
    'title': 'title',
    'to': 'to',
    'toast': 'toast',
    'tobacco': 'tobacco',
    'today': 'today',
    'toddler': 'toddler',
    'toe': 'toe',
    'together': 'together',
    'toil': 'toil',
    'toilet': 'toilet',
    'token': 'token',
    'told': 'tell',
    'tolerance': 'tolerance',
    'tolerant': 'tolerant',
    'toll': 'toll',
    'tomato': 'tomato',
    'tomb': 'tomb',
    'tomorrow': 'tomorrow',
    'tone': 'tone',
    'tongue': 'tongue',
    'tonight': 'tonight',
    'tool': 'tool',
    'tooth': 'tooth',
    'top': 'top',
    'topic': 'topic',
    'torch': 'torch',
    'torment': 'torment',
    'torn': 'tear',
    'tornado': 'tornado',
    'torpedo': 'torpedo',
    'torrent': 'torrent',
    'torso': 'torso',
    'torture': 'torture',
    'toss': 'toss',
    'total': 'total',
    'totally': 'totally',
    'tote': 'tote',
    'touch': 'touch',
    'touching': 'touching',
    'tough': 'tough',
    'tour': 'tour',
    'tourist': 'tourist',
    'tournament': 'tournament',
    'tow': 'tow',
    'toward': 'toward',
    'towards': 'towards',
    'towel': 'towel',
    'tower': 'tower',
    'town': 'town',
    'toxic': 'toxic',
    'toxin': 'toxin',
    'trace': 'trace',
    'track': 'track',
    'tract': 'tract',
    'trade': 'trade',
    'trader': 'trader',
    'tradition': 'tradition',
    'traditional': 'traditional',
    'traffic': 'traffic',
    'tragedy': 'tragedy',
    'tragic': 'tragic',
    'trail': 'trail',
    'trailer': 'trailer',
    'train': 'train',
    'trainee': 'trainee',
    'trainer': 'trainer',
    'trait': 'trait',
    'traitor': 'traitor',
    'tramp': 'tramp',
    'transaction': 'transaction',
    'transcript': 'transcript',
    'transfer': 'transfer',
    'transform': 'transform',
    'transient': 'transient',
    'transistor': 'transistor',
    'transit': 'transit',
    'transition': 'transition',
    'translate': 'translate',
    'translation': 'translation',
    'transmission': 'transmission',
    'transmit': 'transmit',
    'transplant': 'transplant',
    'transport': 'transport',
    'trap': 'trap',
    'trash': 'trash',
    'travel': 'travel',
    'tray': 'tray',
    'treasure': 'treasure',
    'treasury': 'treasury',
    'treat': 'treat',
    'treaty': 'treaty',
    'tree': 'tree',
    'trek': 'trek',
    'tremble': 'tremble',
    'tremendous': 'tremendous',
    'trench': 'trench',
    'trend': 'trend',
    'trendy': 'trendy',
    'trial': 'trial',
    'triangle': 'triangle',
    'tribe': 'tribe',
    'tribute': 'tribute',
    'trick': 'trick',
    'tricky': 'tricky',
    'tried': 'try',
    'trifle': 'trifle',
    'trigger': 'trigger',
    'trillion': 'trillion',
    'trim': 'trim',
    'trio': 'trio',
    'trip': 'trip',
    'triple': 'triple',
    'triumph': 'triumph',
    'trivial': 'trivial',
    'trolley': 'trolley',
    'troop': 'troop',
    'trophy': 'trophy',
    'tropical': 'tropical',
    'trot': 'trot',
    'trouble': 'trouble',
    'troublesome': 'troublesome',
    'trout': 'trout',
    'truck': 'truck',
    'true': 'true',
    'truly': 'truly',
    'trumpet': 'trumpet',
    'trunk': 'trunk',
    'trust': 'trust',
    'truth': 'truth',
    'try': 'try',
    'tub': 'tub',
    'tube': 'tube',
    'tuck': 'tuck',
    'tuesday': 'Tuesday',
    'tug': 'tug',
    'tuition': 'tuition',
    'tumble': 'tumble',
    'tumor': 'tumor',
    'tuna': 'tuna',
    'tune': 'tune',
    'tunnel': 'tunnel',
    'turban': 'turban',
    'turf': 'turf',
    'turkey': 'turkey',
    'turn': 'turn',
    'turnip': 'turnip',
    'turret': 'turret',
    'turtle': 'turtle',
    'tutor': 'tutor',
    'tutorial': 'tutorial',
    'twelve': 'twelve',
    'twenty': 'twenty',
    'twice': 'twice',
    'twig': 'twig',
    'twilight': 'twilight',
    'twin': 'twin',
    'twine': 'twine',
    'twinkle': 'twinkle',
    'twist': 'twist',
    'twitch': 'twitch',
    'two': 'two',
    'type': 'type',
    'typical': 'typical',
    'typist': 'typist',
    'tyranny': 'tyranny',
    'tyrant': 'tyrant',
    'udder': 'udder',
    'ugly': 'ugly',
    'ulcer': 'ulcer',
    'ultimate': 'ultimate',
    'ultimately': 'ultimately',
    'umbrella': 'umbrella',
    'umpire': 'umpire',
    'unable': 'unable',
    'uncle': 'uncle',
    'under': 'under',
    'undergo': 'undergo',
    'undergraduate': 'undergraduate',
    'underground': 'underground',
    'underline': 'underline',
    'underlying': 'underlying',
    'undermine': 'undermine',
    'underneath': 'underneath',
    'understand': 'understand',
    'understanding': 'understanding',
    'undertake': 'undertake',
    'undo': 'undo',
    'undone': 'undo',
    'undoubtedly': 'undoubtedly',
    'unemployed': 'unemployed',
    'unemployment': 'unemployment',
    'unexpected': 'unexpected',
    'unfair': 'unfair',
    'unfold': 'unfold',
    'unfortunate': 'unfortunate',
    'unfortunately': 'unfortunately',
    'unhappy': 'unhappy',
    'unhealthy': 'unhealthy',
    'uniform': 'uniform',
    'union': 'union',
    'unique': 'unique',
    'unit': 'unit',
    'unite': 'unite',
    'united': 'united',
    'unity': 'unity',
    'universal': 'universal',
    'universe': 'universe',
    'university': 'university',
    'unknown': 'unknown',
    'unless': 'unless',
    'unlike': 'unlike',
    'unlikely': 'unlikely',
    'unload': 'unload',
    'unlock': 'unlock',
    'unnecessary': 'unnecessary',
    'unpack': 'unpack',
    'unpaid': 'unpaid',
    'unpopular': 'unpopular',
    'unprecedented': 'unprecedented',
    'unrest': 'unrest',
    'until': 'until',
    'untill': 'until',
    'unusual': 'unusual',
    'unwilling': 'unwilling',
    'up': 'up',
    'update': 'update',
    'upgrade': 'upgrade',
    'uphold': 'uphold',
    'upon': 'upon',
    'upper': 'upper',
    'upright': 'upright',
    'uproar': 'uproar',
    'upset': 'upset',
    'upside': 'upside',
    'upstairs': 'upstairs',
    'upstream': 'upstream',
    'uptown': 'uptown',
    'upward': 'upward',
    'urban': 'urban',
    'urge': 'urge',
    'urgent': 'urgent',
    'urine': 'urine',
    'us': 'us',
    'usage': 'usage',
    'use': 'use',
    'useing': 'using',
    'used': 'use',
    'useful': 'useful',
    'useless': 'useless',
    'user': 'user',
    'usual': 'usual',
    'usually': 'usually',
    'utensil': 'utensil',
    'utility': 'utility',
    'utilize': 'utilize',
    'utmost': 'utmost',
    'utter': 'utter',
    'utterly': 'utterly',
    'vacant': 'vacant',
    'vacation': 'vacation',
    'vaccine': 'vaccine',
    'vacuum': 'vacuum',
    'vague': 'vague',
    'vain': 'vain',
    'valid': 'valid',
    'valley': 'valley',
    'valuable': 'valuable',
    'value': 'value',
    'valve': 'valve',
    'van': 'van',
    'vanish': 'vanish',
    'vanity': 'vanity',
    'vapor': 'vapor',
    'variable': 'variable',
    'variant': 'variant',
    'variation': 'variation',
    'varied': 'varied',
    'variety': 'variety',
    'various': 'various',
    'vary': 'vary',
    'vase': 'vase',
    'vast': 'vast',
    'vault': 'vault',
    'vector': 'vector',
    'vegetable': 'vegetable',
    'vehicle': 'vehicle',
    'veil': 'veil',
    'vein': 'vein',
    'velvet': 'velvet',
    'vendor': 'vendor',
    'venture': 'venture',
    'venue': 'venue',
    'verb': 'verb',
    'verbal': 'verbal',
    'verdict': 'verdict',
    'verge': 'verge',
    'verify': 'verify',
    'verse': 'verse',
    'version': 'version',
    'versus': 'versus',
    'vertical': 'vertical',
    'very': 'very',
    'vessel': 'vessel',
    'veteran': 'veteran',
    'veterinary': 'veterinary',
    'veto': 'veto',
    'via': 'via',
    'vibrant': 'vibrant',
    'vibrate': 'vibrate',
    'vice': 'vice',
    'victim': 'victim',
    'victory': 'victory',
    'video': 'video',
    'view': 'view',
    'viewer': 'viewer',
    'viewpoint': 'viewpoint',
    'vigor': 'vigor',
    'vigorous': 'vigorous',
    'vile': 'vile',
    'village': 'village',
    'villain': 'villain',
    'vine': 'vine',
    'vinegar': 'vinegar',
    'violate': 'violate',
    'violation': 'violation',
    'violence': 'violence',
    'violent': 'violent',
    'violet': 'violet',
    'violin': 'violin',
    'viral': 'viral',
    'virgin': 'virgin',
    'virtual': 'virtual',
    'virtue': 'virtue',
    'virus': 'virus',
    'visa': 'visa',
    'visibility': 'visibility',
    'visible': 'visible',
    'vision': 'vision',
    'visit': 'visit',
    'visitor': 'visitor',
    'visual': 'visual',
    'visualize': 'visualize',
    'vital': 'vital',
    'vivid': 'vivid',
    'vocal': 'vocal',
    'vocation': 'vocation',
    'voice': 'voice',
    'void': 'void',
    'volatile': 'volatile',
    'volcano': 'volcano',
    'volley': 'volley',
    'voltage': 'voltage',
    'volume': 'volume',
    'voluntary': 'voluntary',
    'volunteer': 'volunteer',
    'vomit': 'vomit',
    'vote': 'vote',
    'voter': 'voter',
    'vouch': 'vouch',
    'voucher': 'voucher',
    'vow': 'vow',
    'vowel': 'vowel',
    'voyage': 'voyage',
    'vulgar': 'vulgar',
    'vulnerable': 'vulnerable',
    'wade': 'wade',
    'wafer': 'wafer',
    'wage': 'wage',
    'wagon': 'wagon',
    'wail': 'wail',
    'waist': 'waist',
    'wait': 'wait',
    'waiter': 'waiter',
    'wake': 'wake',
    'waken': 'waken',
    'walk': 'walk',
    'wall': 'wall',
    'wallet': 'wallet',
    'walnut': 'walnut',
    'waltz': 'waltz',
    'wand': 'wand',
    'wander': 'wander',
    'want': 'want',
    'war': 'war',
    'warden': 'warden',
    'warm': 'warm',
    'warmth': 'warmth',
    'warn': 'warn',
    'warning': 'warning',
    'warrant': 'warrant',
    'warrior': 'warrior',
    'wary': 'wary',
    'wash': 'wash',
    'waste': 'waste',
    'watch': 'watch',
    'water': 'water',
    'waterfall': 'waterfall',
    'waterproof': 'waterproof',
    'watt': 'watt',
    'wave': 'wave',
    'waver': 'waver',
    'wavy': 'wavy',
    'wax': 'wax',
    'way': 'way',
    'we': 'we',
    'weak': 'weak',
    'weaken': 'weaken',
    'weakness': 'weakness',
    'wealth': 'wealth',
    'wealthy': 'wealthy',
    'weapon': 'weapon',
    'wear': 'wear',
    'weary': 'weary',
    'weather': 'weather',
    'weave': 'weave',
    'weaver': 'weaver',
    'web': 'web',
    'website': 'website',
    'wed': 'wed',
    'wedding': 'wedding',
    'wedge': 'wedge',
    'wednesday': 'Wednesday',
    'weed': 'weed',
    'week': 'week',
    'weekday': 'weekday',
    'weekend': 'weekend',
    'weekly': 'weekly',
    'weep': 'weep',
    'weigh': 'weigh',
    'weight': 'weight',
    'weird': 'weird',
    'welcome': 'welcome',
    'welfare': 'welfare',
    'well': 'well',
    'went': 'go',
    'wept': 'weep',
    'were': 'are',
    'west': 'west',
    'western': 'western',
    'wet': 'wet',
    'whale': 'whale',
    'wharf': 'wharf',
    'what': 'what',
    'whatever': 'whatever',
    'wheat': 'wheat',
    'wheel': 'wheel',
    'when': 'when',
    'whenever': 'whenever',
    'where': 'where',
    'wheras': 'whereas',
    'whereas': 'whereas',
    'wherever': 'wherever',
    'whether': 'whether',
    'which': 'which',
    'wich': 'which',
    'whichever': 'whichever',
    'while': 'while',
    'whim': 'whim',
    'whine': 'whine',
    'whip': 'whip',
    'whirl': 'whirl',
    'whisk': 'whisk',
    'whisker': 'whisker',
    'whiskey': 'whiskey',
    'whisper': 'whisper',
    'whistle': 'whistle',
    'white': 'white',
    'who': 'who',
    'whoever': 'whoever',
    'whole': 'whole',
    'whom': 'whom',
    'whose': 'whose',
    'wicked': 'wicked',
    'wide': 'wide',
    'widely': 'widely',
    'widen': 'widen',
    'widespread': 'widespread',
    'widow': 'widow',
    'widower': 'widower',
    'width': 'width',
    'wife': 'wife',
    'wild': 'wild',
    'wildly': 'wildly',
    'will': 'will',
    'willing': 'willing',
    'willow': 'willow',
    'win': 'win',
    'wince': 'wince',
    'wind': 'wind',
    'window': 'window',
    'windy': 'windy',
    'wine': 'wine',
    'wing': 'wing',
    'wink': 'wink',
    'winner': 'winner',
    'winter': 'winter',
    'wipe': 'wipe',
    'wire': 'wire',
    'wireless': 'wireless',
    'wisdom': 'wisdom',
    'wise': 'wise',
    'wisely': 'wisely',
    'wish': 'wish',
    'wisp': 'wisp',
    'wit': 'wit',
    'witch': 'witch',
    'with': 'with',
    'withdraw': 'withdraw',
    'withdrawal': 'withdrawal',
    'wither': 'wither',
    'within': 'within',
    'without': 'without',
    'witness': 'witness',
    'witty': 'witty',
    'wives': 'wife',
    'wizard': 'wizard',
    'woke': 'wake',
    'woken': 'wake',
    'wolf': 'wolf',
    'woman': 'woman',
    'women': 'woman',
    'wonder': 'wonder',
    'wonderful': 'wonderful',
    'wont': "won't",
    'wood': 'wood',
    'wooden': 'wooden',
    'woodwork': 'woodwork',
    'wool': 'wool',
    'woolen': 'woolen',
    'word': 'word',
    'wordy': 'wordy',
    'work': 'work',
    'worker': 'worker',
    'workforce': 'workforce',
    'working': 'working',
    'workout': 'workout',
    'workplace': 'workplace',
    'workshop': 'workshop',
    'world': 'world',
    'worldwide': 'worldwide',
    'worm': 'worm',
    'worn': 'wear',
    'worried': 'worried',
    'worry': 'worry',
    'worse': 'worse',
    'worsen': 'worsen',
    'worship': 'worship',
    'worst': 'worst',
    'worth': 'worth',
    'worthwhile': 'worthwhile',
    'worthy': 'worthy',
    'would': 'would',
    'wound': 'wound',
    'wove': 'weave',
    'woven': 'weave',
    'wrap': 'wrap',
    'wrapper': 'wrapper',
    'wrath': 'wrath',
    'wreath': 'wreath',
    'wreck': 'wreck',
    'wrench': 'wrench',
    'wrestle': 'wrestle',
    'wretched': 'wretched',
    'wriggle': 'wriggle',
    'wring': 'wring',
    'wrinkle': 'wrinkle',
    'wrist': 'wrist',
    'write': 'write',
    'writer': 'writer',
    'writhe': 'writhe',
    'written': 'write',
    'wrong': 'wrong',
    'wrote': 'write',
    'wrung': 'wring',
    'yacht': 'yacht',
    'yard': 'yard',
    'yarn': 'yarn',
    'year': 'year',
    'yearly': 'yearly',
    'yearn': 'yearn',
    'yeast': 'yeast',
    'yell': 'yell',
    'yellow': 'yellow',
    'yelp': 'yelp',
    'yes': 'yes',
    'yesterday': 'yesterday',
    'yet': 'yet',
    'yield': 'yield',
    'yoke': 'yoke',
    'yolk': 'yolk',
    'you': 'you',
    'young': 'young',
    'youngster': 'youngster',
    'your': 'your',
    'yours': 'yours',
    'yourself': 'yourself',
    'youth': 'youth',
    'youthful': 'youthful',
    'zeal': 'zeal',
    'zealous': 'zealous',
    'zebra': 'zebra',
    'zero': 'zero',
    'zest': 'zest',
    'zinc': 'zinc',
    'zone': 'zone',
    'zoo': 'zoo',
    'zoom': 'zoom',
    'sequensing': 'sequencing',
    'amplifcation': 'amplification',
    'hybrization': 'hybridization',
    'denaturtion': 'denaturation',
    'anealing': 'annealing',
    'elongtion': 'elongation',
    'purifcation': 'purification',
    'centrifigation': 'centrifugation',
    'electrophresis': 'electrophoresis',
    'chromatograpy': 'chromatography',
    'spectophotometer': 'spectrophotometer',
    'fluoroscence': 'fluorescence',
    'oligonucletide': 'oligonucleotide',
    'nucletide': 'nucleotide',
    'restiction': 'restriction',
    'fragmenttion': 'fragmentation',
    'transformtion': 'transformation',
    'clonning': 'cloning',
    'genom': 'genome',
    'proteom': 'proteome',
    'epigenom': 'epigenome',
    'microbiom': 'microbiome',
    'phylogentic': 'phylogenetic',
    'homologus': 'homologous',
    'orthologus': 'orthologous',
    'paralogus': 'paralogous',
    'heterologus': 'heterologous',
    'polymorhpism': 'polymorphism',
    'mutaion': 'mutation',
    'varaint': 'variant',
    'allel': 'allele',
    'genotye': 'genotype',
    'phenotye': 'phenotype',
    'haplotye': 'haplotype',
    'purifcation': 'purification',
    'centrifigation': 'centrifugation',
    'electrophresis': 'electrophoresis',
    'chromatograpy': 'chromatography',
    'spectophotometer': 'spectrophotometer',
    'fluoroscence': 'fluorescence',
    'hybrization': 'hybridization',
    'denaturtion': 'denaturation',
    'anealing': 'annealing',
    'elongtion': 'elongation',
    'transcriptom': 'transcriptome',
    'metabolom': 'metabolome',
    'mgisp': 'MGISP',
    'dnblab': 'DNBelab',
}

FORCED_MISSPELLINGS = {
    'bindind',
    'calibratation',
    'complet',
    'deteced',
    'equipement',
    'instalation',
    'keeped',
    'maintainance',
    'performace',
    'platfoms',
    'sensetivity',
    'sensitivty',
}


def _is_technical_term(word):
    """检查是否是技术文档常用术语"""
    token = str(word or '').strip('.')
    return _is_protected_technical_token(token)


def _is_domain_abbreviation(word):
    token = word.strip('.').lower()
    return token in DOMAIN_ABBREVIATIONS


def _normalize_for_check(word):
    """标准化单词用于拼写检查"""
    w = word.strip('.')
    return w.lower()


def _extract_chapter(content, position):
    lines = content[:position].split('\n')
    for i in range(len(lines) - 1, max(-1, len(lines) - 25), -1):
        line = lines[i].strip()
        if not line:
            continue
        if line.startswith('#'):
            return line.lstrip('#').strip()
        if re.match(r'^\d+(?:\.\d+)*(?:[\)\.])?\s*[A-Z][^\n]{2,}$', line):
            return re.sub(r'^(\d+(?:\.\d+)*)([A-Z])', r'\1 \2', line)
    return ''


def _is_dictionary_word(token):
    lowered = token.lower()
    if not lowered:
        return False
    if lowered in _JOINER_SMALL_WORDS:
        return True
    if _is_technical_term(token):
        return True
    if _is_domain_abbreviation(token):
        return True
    return lowered in spell


def _is_extraction_artifact(word):
    lowered = word.lower()
    if not lowered.startswith('y') or len(word) <= 2:
        return False
    rest = word[1:]
    if not rest:
        return False
    return (
        _is_dictionary_word(rest.lower())
        or _is_technical_term(rest)
        or _is_domain_abbreviation(rest)
        or rest.lower() in COMMON_MISSPELLINGS
    )


def _looks_like_joined_words(word):
    lowered = word.lower()
    if len(lowered) < 5 or not lowered.isalpha():
        return False

    memo = {}

    def can_split(start, parts):
        key = (start, parts)
        if key in memo:
            return memo[key]
        if start == len(lowered):
            return parts >= 2
        if parts >= 3:
            return False

        upper = min(len(lowered), start + 12)
        for end in range(start + 2, upper + 1):
            piece = lowered[start:end]
            if not _is_dictionary_word(piece):
                continue
            if can_split(end, parts + 1):
                memo[key] = True
                return True

        memo[key] = False
        return False

    return can_split(0, 0)


def _should_skip_spelling_issue(word, context, file_type=None):
    if is_whitelisted(word) or _is_domain_abbreviation(word) or _is_extraction_artifact(word):
        return True

    if _normalize_for_check(word) == 'equipement' and re.search(r'personal\s+protective\s+equipement\s*\(\s*PPE\s*\)', context or '', re.IGNORECASE):
        return True

    if _normalize_for_check(word) in FORCED_MISSPELLINGS:
        return False

    if re.search(r'@|https?://|www\.', context or '', re.IGNORECASE):
        return True

    if re.search(rf'\b{re.escape(word)}\s+[a-z]{{1,2}}\b', context, re.IGNORECASE):
        joined = re.sub(rf'\b{re.escape(word)}\s+([a-z]{{1,2}})\b', lambda match: word + match.group(1), context, flags=re.IGNORECASE)
        if re.search(r'\bsupernatant\b', joined, re.IGNORECASE):
            return True

    if file_type != 'pdf':
        return False

    if word.lower() in _PDF_SPELL_SKIP_WORDS:
        return True

    if _looks_like_joined_words(word):
        return True

    lowered = word.lower()
    fragment_hits = sum(1 for fragment in _PDF_TECH_FRAGMENTS if fragment in lowered)
    if fragment_hits >= 2:
        return True
    if lowered.endswith('dnb') and lowered[:2] in {'of', 'to', 'in'}:
        return True
    if lowered.startswith('coli') and 'and' in lowered:
        return True
    if re.match(r'^(?:ii|iii|iv|vi)+[a-z]+$', lowered):
        return True

    compact_tokens = re.findall(r'\b[a-z]{8,}\b', context.lower())
    merged_like_count = sum(1 for token in compact_tokens if _looks_like_joined_words(token))
    return merged_like_count >= 2


def _build_spelling_context(content, start, end, radius=90):
    context_start = max(0, start - radius)
    context_end = min(len(content), end + radius)
    return re.sub(r'\s+', ' ', content[context_start:context_end]).strip()


def _format_spelling_suggestion(word, context, suggestions, certainty='疑似'):
    suggestion_part = '、'.join(str(item) for item in suggestions if item)
    return suggestion_part


def check_spelling(content, min_word_length=3, file_type=None):
    """
    检查英文文档的拼写错误
    返回拼写错误列表
    """
    issues = []
    seen_issue_keys = set()

    for typo in FORCED_MISSPELLINGS:
        correct = COMMON_MISSPELLINGS.get(typo)
        if not correct:
            continue
        normalized = _normalize_for_check(typo)
        if normalized == _normalize_for_check(correct):
            continue
        for match in re.finditer(r'\b' + re.escape(typo) + r'\b', content, re.IGNORECASE):
            word = match.group(0)
            if len(word) < min_word_length or is_whitelisted(word):
                continue
            if _is_technical_term(word) or _is_domain_abbreviation(word) or _is_extraction_artifact(word):
                continue
            context = _build_spelling_context(content, match.start(), match.end())
            if _should_skip_spelling_issue(word, context, file_type):
                continue
            dedupe_key = (normalized, 'spell', match.start())
            if dedupe_key in seen_issue_keys:
                continue
            seen_issue_keys.add(dedupe_key)
            chapter = _extract_chapter(content, match.start())
            issues.append({
                "severity": "serious",
                "category": "拼写/用词错误",
                "rule": "SPELL",
                "chapter": chapter,
                "original_text": word,
                "context": context,
                "suggestion": _format_spelling_suggestion(word, context, [correct], '确定'),
                "description": f"原文片段：'{context}'；疑似错误词：[{word}]；建议修改词：[{correct}]；是否确定：确定。",
                "audit_basis": "英文拼写规范",
                "confidence": 95,
                "source": "spellcheck",
                "position": f"{match.start()}-{match.end()}"
            })
    
    # 提取所有单词
    words = re.findall(r"[a-zA-Z]+(?:'[a-zA-Z]+)?", content)
    
    # 使用 spellchecker 检查
    misspelled = spell.unknown(words)
    
    for word in misspelled:
        # 跳过太短的词
        if len(word) < min_word_length:
            continue

        if is_whitelisted(word):
            continue

        # 跳过技术术语白名单
        if _is_technical_term(word) or _is_domain_abbreviation(word) or _is_extraction_artifact(word):
            continue
        
        # 检查常见错误映射表
        normalized = _normalize_for_check(word)
        if normalized in COMMON_MISSPELLINGS:
            correct = COMMON_MISSPELLINGS[normalized]
            # 找到单词在文档中的位置
            for match in re.finditer(r'\b' + re.escape(word) + r'\b', content, re.IGNORECASE):
                context = _build_spelling_context(content, match.start(), match.end())
                if _should_skip_spelling_issue(word, context, file_type):
                    continue
                dedupe_key = (normalized, 'spell', match.start())
                if dedupe_key in seen_issue_keys:
                    continue
                seen_issue_keys.add(dedupe_key)
                chapter = _extract_chapter(content, match.start())
                
                issues.append({
                    "severity": "serious",
                    "category": "拼写/用词错误",
                    "rule": "SPELL",
                    "chapter": chapter,
                    "original_text": word,
                    "context": context,
                    "suggestion": _format_spelling_suggestion(word, context, [correct], '确定'),
                    "description": f"原文片段：'{context}'；疑似错误词：[{word}]；建议修改词：[{correct}]；是否确定：确定。",
                    "audit_basis": "英文拼写规范",
                    "confidence": 95,
                    "source": "spellcheck",
                    "position": f"{match.start()}-{match.end()}"
                })
        else:
            # 使用 spellchecker 的建议
            suggestions = list(spell.candidates(word) or [])[:3]
            if not suggestions:
                continue
            
            for match in re.finditer(r'\b' + re.escape(word) + r'\b', content, re.IGNORECASE):
                context = _build_spelling_context(content, match.start(), match.end())
                if _should_skip_spelling_issue(word, context, file_type):
                    continue
                dedupe_key = (normalized, 'spell')
                if dedupe_key in seen_issue_keys:
                    continue
                seen_issue_keys.add(dedupe_key)
                chapter = _extract_chapter(content, match.start())
                
                issues.append({
                    "severity": "general",
                    "category": "拼写/用词错误",
                    "rule": "SPELL",
                    "chapter": chapter,
                    "original_text": word,
                    "context": context,
                    "suggestion": _format_spelling_suggestion(word, context, suggestions, '疑似'),
                    "description": f"原文片段：'{context}'；疑似错误词：[{word}]；建议修改词：[{', '.join(suggestions)}]；是否确定：疑似。",
                    "audit_basis": "英文拼写规范",
                    "confidence": 80,
                    "source": "spellcheck",
                    "position": f"{match.start()}-{match.end()}"
                })
    
    return issues


def _is_vowel_sound(word):
    token = (word or '').strip('.,;:()[]{}"\'').strip()
    if not token:
        return False

    lower = token.lower()
    if re.match(r'^(honest|hour|honor|heir)', lower):
        return True
    if re.match(r'^(university|universal|user|unit|unique|european|eucalyptus|one|one-step)', lower):
        return False
    if token.isupper() and token[0] in set('AEFHILMNORSX'):
        return True
    return lower[0] in 'aeiou'


def check_grammar_patterns(content):
    """检查技术文档中的高置信语法问题。"""
    issues = []
    seen = set()

    def add_issue(start, end, original_text, suggestion, description, confidence=80):
        key = (start, end, suggestion)
        if key in seen:
            return
        seen.add(key)
        context_start = max(0, start - 50)
        context_end = min(len(content), end + 50)
        context = content[context_start:context_end]
        issues.append({
            "severity": "general",
            "category": "冠词错误",
            "rule": "GRAMMAR",
            "chapter": _extract_chapter(content, start),
            "original_text": original_text,
            "context": context,
            "suggestion": suggestion,
            "description": description,
            "audit_basis": "英语语法规范",
            "confidence": confidence,
            "source": "grammar",
            "position": f"{start}-{end}"
        })

    for match in re.finditer(r'\b(a|an)\s+([A-Za-z][A-Za-z0-9\-]*)', content):
        article = match.group(1).lower()
        noun = match.group(2)
        vowel_sound = _is_vowel_sound(noun)
        if article == 'a' and vowel_sound:
            add_issue(match.start(), match.end(), match.group(0), f"建议改为: an {noun}", "元音发音开头的单词前应使用 an")
        if article == 'an' and not vowel_sound:
            add_issue(match.start(), match.end(), match.group(0), f"建议改为: a {noun}", "辅音发音开头的单词前应使用 a")

    return issues


def run_spelling_and_grammar_check(content, file_type=None):
    """
    综合拼写和语法检查
    返回所有发现的问题
    """
    all_issues = []
    
    # 1. 拼写检查
    spelling_issues = check_spelling(content, file_type=file_type)
    all_issues.extend(spelling_issues)
    
    # 2. 语法模式检查
    grammar_issues = check_grammar_patterns(content)
    all_issues.extend(grammar_issues)
    
    return all_issues
